### ISSUE TITLE
Slave containers coming up with duplicate binding. Jenkins can't connect to slave.

### ISSUE THREAD

**Issue by Sulphurium-Brimstone** [jenkinsci/docker-plugin#842] opened 2021-07-23 19:16 UTC
**Issue blocking development.**

### Versions:
 - docker-plugin: 1.2.2
 - docker-commons: 1.17
 - docker-java-api: 3.1.5.2
 -  ssh-agent: 1.20
 - jenkins: 2.263.3
 - docker engine: 20.10.7

### Overview:
Jenkins connects to dynamic slaves (docker-cloud) via ssh. Slave container is coming up with two IPv4 mapping to port 22. Both for the same IPv4 address, just different external ports (sometimes). When the they are the same Jenkins can attach to the slave. When different Jenkins cannot attach. Jenkins always tries to attach to first port mapping. Did not see this behavior before upgrading to the current versions. Old behavior was only one port mapping to 22.

They are different ports more than the same. Adds massive delays to pipelines or they never run. 

Restarting docker causes the double port mappings to sync for a little while. Therefore, allowing Jenkins to connect to slaves again. However this is not a work around as it breaks (un-syncs) quickly as well as requires all swarm hosts to be reset.

### Docker Agent Template Settings(non-default values):
     Labels: centos7-standalone-py3
     Name: centos7-py3
     Enabled: True
     Docker Image: msthoth:5000/centos7-standalone-py3:1
     Volumes: /var/run/docker.sock:/var/run/docker.sock     /home/jenkins
     Remote File System Root: /home/jenkins
     Idle timeout: 20
     Connect method: Connect with SSH
          SSH Key: Use configured SSH credentials
          Port: 22
          JVM Options: -Xms1G  -Xmx2G -Xss256k -server -XX:+AlwaysPreTouch -XX:+UseG1GC -XX:+ExplicitGCInvokesConcurrent -XX:+ParallelRefProcEnabled -XX:+UseStringDeduplication -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:+UnlockDiagnosticVMOptions -XX:G1SummarizeRSetStatsPeriod=1
          Connection Timeout in Seconds: 210
          Maximum Number of Retries: 10
          Seconds To Wait Between Retries: 15
     Stop timeout: 0
     Pull strategy: Pull once and update latest
     Pull timeout: 300

### Jenkins Log:

Jul 23, 2021 6:12:15 PM WARNING com.nirima.jenkins.plugins.docker.utils.PortUtils$ConnectionCheck execute
Could not connect to 128.x.x.x port 50010. Are you sure this location is contactable from Jenkins?
Jul 23, 2021 6:12:15 PM SEVERE com.github.dockerjava.core.async.ResultCallbackTemplate onError
Error during callback
com.github.dockerjava.api.exception.NotFoundException: Container 5c86b0a85e06c5088d2a23e44c851ba4f0058a0b1246861b2e667337622afc72 not found

	at com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:103)
	at com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:33)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHanddlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

Jul 23, 2021 6:12:15 PM INFO com.nirima.jenkins.plugins.docker.DockerTemplate doProvisionNode
Unable to remove container '5c86b0a85e06c5088d2a23e44c851ba4f0058a0b1246861b2e667337622afc72' as it had already gone.
Jul 23, 2021 6:12:15 PM SEVERE com.nirima.jenkins.plugins.docker.DockerCloud$1 run
Error in provisioning; template='DockerTemplate{configVersion=2, labelString='centos7-standalone-py3', connector=DockerComputerSSHConnector{sshKeyStrategy=ManuallyConfiguredSSHKey{credentialsId='afb77a26-b5e1-4658-9370-b895121536ad', sshHostKeyVerificationStrategy=hudson.plugins.sshslaves.verifiers.NonVerifyingKeyVerificationStrategy@61e8a1e4}, port=22, jvmOptions='-Xms1G  -Xmx2G -Xss256k -server -XX:+AlwaysPreTouch -XX:+UseG1GC -XX:+ExplicitGCInvokesConcurrent -XX:+ParallelRefProcEnabled -XX:+UseStringDeduplication -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:+UnlockDiagnosticVMOptions -XX:G1SummarizeRSetStatsPeriod=1', launchTimeoutSeconds=210, maxNumRetries=10, retryWaitTime=15}, remoteFs='/home/jenkins', instanceCap=2147483647, mode=EXCLUSIVE, retentionStrategy=com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy@33, dockerTemplateBase=DockerTemplateBase{image='msthoth:5000/centos7-standalone-py3:1', volumes=[/var/run/docker.sock:/var/run/docker.sock, /home/jenkins], bindAllPorts=false, cpuPeriod=0, cpuQuota=0, privileged=false, tty=false}, removeVolumes=false, stopTimeout=0, pullStrategy=PULL_LATEST, pullTimeout=300, nodeProperties=[hudson.slaves.EnvironmentVariablesNodeProperty@15dda5d4], disabled=BySystem,0 ms,4.9 sec,Template provisioning failed., name='centos7-py3'}' for cloud='thoth-swarm'
java.io.IOException: SSH service hadn't started after 150 seconds and 10 milliseconds.Try increasing the number of retries (currently 10) and/or the retry wait time (currently 15) to allow for containers taking longer to start.

	at io.jenkins.docker.connector.DockerComputerSSHConnector.createLauncher(DockerComputerSSHConnector.java:317)
	at io.jenkins.docker.connector.DockerComputerConnector.createLauncher(DockerComputerConnector.java:142)
	at com.nirima.jenkins.plugins.docker.DockerTemplate.doProvisionNode(DockerTemplate.java:739)
	at com.nirima.jenkins.plugins.docker.DockerTemplate.provisionNode(DockerTemplate.java:676)
	at com.nirima.jenkins.plugins.docker.DockerCloud$1.run(DockerCloud.java:375)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Jul 23, 2021 6:12:24 PM WARNING hudson.slaves.NodeProvisioner lambda$update$6
Unexpected exception encountered while provisioning agent Image of msthoth:5000/centos7-standalone-py3:1
java.io.IOException: SSH service hadn't started after 150 seconds and 10 milliseconds.Try increasing the number of retries (currently 10) and/or the retry wait time (currently 15) to allow for containers taking longer to start.

	at io.jenkins.docker.connector.DockerComputerSSHConnector.createLauncher(DockerComputerSSHConnector.java:317)
	at io.jenkins.docker.connector.DockerComputerConnector.createLauncher(DockerComputerConnector.java:142)
	at com.nirima.jenkins.plugins.docker.DockerTemplate.doProvisionNode(DockerTemplate.java:739)
	at com.nirima.jenkins.plugins.docker.DockerTemplate.provisionNode(DockerTemplate.java:676)
	at com.nirima.jenkins.plugins.docker.DockerCloud$1.run(DockerCloud.java:375)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

### Slave running with port 22 mapped twice. 
	[jenkins@msthoth ~]$ docker -H tcp://msthoth:4000 ps -a
	CONTAINER ID   IMAGE                                   COMMAND                  CREATED              STATUS              PORTS                                                                  NAMES
	5c86b0a85e06   msthoth:5000/centos7-standalone-py3:1   "/usr/sbin/sshd -D -…"   About a minute ago   Up About a minute   5900/tcp, 128.x.x.x:50010->22/tcp, 128.x.x.x:50110->22/tcp   ms-ci-vb01/angry_mendeleev

**Comment by mikjonsson** [comment] 2021-08-17 07:36
This is potentially the same issue as https://github.com/jenkinsci/docker-plugin/issues/839 - What do you think?

**Comment by Sulphurium-Brimstone** [comment] 2021-08-20 17:23
Yes it sounds like they are the same or at least the same root cause.

**Comment by pjdarton** [comment] 2022-06-09 12:44
Closing as duplicate of #839

**Closed by pjdarton** 2022-06-09 12:44 UTC
