### ISSUE TITLE
Private DockerHub Repository cannot pull agent for labeled agent build

### ISSUE THREAD

**Issue by FeynmanFan** [jenkinsci/docker-plugin#784] opened 2020-04-02 23:38 UTC
I've provisioned a cloud agent here - https://hub.docker.com/repository/docker/chrisbbehrens/agent-dnc. When this repo is public, the agent provisioning works fine, and a build assigned to its label builds correctly.

When I make the repo private, and assign the DockerHub creds to the agent in the Agent template, the agent cannot be provisioned, and the build sits at 'Jenkins' doesn't have label 'LABEL' forever. Here are the contents of the log around this agent:

```
Cached connection io.jenkins.docker.client.DockerAPI$SharableDockerClient@231ac40a to DockerClientParameters{dockerUri=tcp://host.docker.internal:2375, credentialsId=null, readTimeoutInMsOrNull=60000, connectTimeoutInMsOrNull=60000}
Apr 02, 2020 11:18:28 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud canAddProvisionedSlave
Provisioning 'chrisbbehrens/agent-dnc:v4' number 1 (of 10) on 'docker'; Total containers: 0 (of 100)
Apr 02, 2020 11:18:28 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud provision
Will provision 'chrisbbehrens/agent-dnc:v4', for label: 'DOTNETCORE', in cloud: 'docker'
Apr 02, 2020 11:18:28 PM INFO hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
Started provisioning Image of chrisbbehrens/agent-dnc:v4 from docker with 1 executors. Remaining excess workload: 0
Apr 02, 2020 11:18:28 PM INFO com.nirima.jenkins.plugins.docker.DockerTemplate pullImage
Pulling image 'chrisbbehrens/agent-dnc:v4'. This may take awhile...
Apr 02, 2020 11:18:28 PM INFO io.jenkins.docker.client.DockerAPI getOrMakeClient
Cached connection io.jenkins.docker.client.DockerAPI$SharableDockerClient@38419f0 to DockerClientParameters{dockerUri=tcp://host.docker.internal:2375, credentialsId=null, readTimeoutInMsOrNull=300000, connectTimeoutInMsOrNull=60000}
```

A successful provisioning in another build for another public agent looks like this in the logs:

```
Asked to provision 1 slave(s) for: docker
Apr 02, 2020 11:35:12 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud canAddProvisionedSlave
Provisioning 'chrisbbehrens/jenkinsdocker:v1' on 'docker'; Total containers: 0 (of 100)
Apr 02, 2020 11:35:12 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud provision
Will provision 'chrisbbehrens/jenkinsdocker:v1', for label: 'docker', in cloud: 'docker'
Apr 02, 2020 11:35:12 PM INFO hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
Started provisioning Image of chrisbbehrens/jenkinsdocker:v1 from docker with 1 executors. Remaining excess workload: 0
Apr 02, 2020 11:35:12 PM INFO com.nirima.jenkins.plugins.docker.DockerTemplate pullImage
Pulling image 'chrisbbehrens/jenkinsdocker:v1'. This may take awhile...
Apr 02, 2020 11:35:12 PM INFO io.jenkins.docker.client.DockerAPI getOrMakeClient
Cached connection io.jenkins.docker.client.DockerAPI$SharableDockerClient@98e64c2 to DockerClientParameters{dockerUri=tcp://host.docker.internal:2375, credentialsId=null, readTimeoutInMsOrNull=300000, connectTimeoutInMsOrNull=60000}
Apr 02, 2020 11:35:13 PM INFO com.nirima.jenkins.plugins.docker.DockerTemplate pullImage
Finished pulling image 'chrisbbehrens/jenkinsdocker:v1', took 927 ms
Apr 02, 2020 11:35:13 PM INFO com.nirima.jenkins.plugins.docker.DockerTemplate doProvisionNode
Trying to run container for chrisbbehrens/jenkinsdocker:v1
Apr 02, 2020 11:35:13 PM INFO com.nirima.jenkins.plugins.docker.DockerTemplate doProvisionNode
Trying to run container for node Docker builder image-0000i1zamejp6 from image: chrisbbehrens/jenkinsdocker:v1
Apr 02, 2020 11:35:14 PM INFO com.nirima.jenkins.plugins.docker.DockerTemplate doProvisionNode
Started container ID 298fa6f10321824a1d4125a755569f078aa2f3070b61f07e57e17d96fc381bf6 for node Docker builder image-0000i1zamejp6 from image: chrisbbehrens/jenkinsdocker:v1
Apr 02, 2020 11:35:16 PM WARNING io.jenkins.docker.client.DockerMultiplexedInputStream readInternal
Unexpected data on container stderr: Apr 02, 2020 11:35:16 PM org.jenkinsci.remoting.engine.WorkDirManager setupLogging
INFO: Using /agent.log as an agent error log destination; output log will not be generated

Apr 02, 2020 11:35:17 PM WARNING io.jenkins.docker.client.DockerMultiplexedInputStream readInternal
Unexpected data on container stderr: channel started

Apr 02, 2020 11:35:20 PM INFO hudson.slaves.NodeProvisioner lambda$update$6
Image of chrisbbehrens/jenkinsdocker:v1 provisioning successfully completed. We have now 2 computer(s)
Apr 02, 2020 11:36:23 PM INFO hudson.remoting.SynchronousCommandTransport$ReaderThread run
I/O error in channel Docker builder image-0000i1zamejp6
java.net.SocketException: Socket closed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at io.jenkins.docker.client.DockerMultiplexedInputStream.readInternal(DockerMultiplexedInputStream.java:48)
	at io.jenkins.docker.client.DockerMultiplexedInputStream.read(DockerMultiplexedInputStream.java:30)
	at hudson.remoting.FlightRecorderInputStream.read(FlightRecorderInputStream.java:91)
	at hudson.remoting.ChunkedInputStream.readHeader(ChunkedInputStream.java:72)
	at hudson.remoting.ChunkedInputStream.readUntilBreak(ChunkedInputStream.java:103)
	at hudson.remoting.ChunkedCommandTransport.readBlock(ChunkedCommandTransport.java:39)
	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:63)

Apr 02, 2020 11:36:23 PM WARNING hudson.remoting.Request$2 run
Failed to send back a reply to the request hudson.remoting.Request$2@f4f1a3e
java.net.SocketException: Socket closed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at io.jenkins.docker.client.DockerMultiplexedInputStream.readInternal(DockerMultiplexedInputStream.java:48)
	at io.jenkins.docker.client.DockerMultiplexedInputStream.read(DockerMultiplexedInputStream.java:30)
	at hudson.remoting.FlightRecorderInputStream.read(FlightRecorderInputStream.java:91)
	at hudson.remoting.ChunkedInputStream.readHeader(ChunkedInputStream.java:72)
	at hudson.remoting.ChunkedInputStream.readUntilBreak(ChunkedInputStream.java:103)
	at hudson.remoting.ChunkedCommandTransport.readBlock(ChunkedCommandTransport.java:39)
	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:63)
Caused: hudson.remoting.ChannelClosedException: Channel "hudson.remoting.Channel@32b58ba7:Docker builder image-0000i1zamejp6": channel is already closed
	at hudson.remoting.Channel.send(Channel.java:760)
	at hudson.remoting.Request$2.run(Request.java:382)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at org.jenkinsci.remoting.CallableDecorator.call(CallableDecorator.java:18)
	at hudson.remoting.CallableDecoratorList$1.call(CallableDecoratorList.java:21)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Apr 02, 2020 11:36:23 PM INFO io.jenkins.docker.DockerTransientNode$1 println
Disconnected computer for node 'Docker builder image-0000i1zamejp6'.
Apr 02, 2020 11:36:23 PM INFO io.jenkins.docker.DockerTransientNode$1 println
Removed Node for node 'Docker builder image-0000i1zamejp6'.
Apr 02, 2020 11:36:23 PM INFO org.jenkinsci.plugins.workflow.job.WorkflowRun finish
Build Agent-DNC #5 completed: SUCCESS
Apr 02, 2020 11:36:33 PM INFO io.jenkins.docker.DockerTransientNode$1 println
Stopped container '298fa6f10321824a1d4125a755569f078aa2f3070b61f07e57e17d96fc381bf6' for node 'Docker builder image-0000i1zamejp6'.
Apr 02, 2020 11:36:33 PM INFO io.jenkins.docker.DockerTransientNode$1 println
Removed container '298fa6f10321824a1d4125a755569f078aa2f3070b61f07e57e17d96fc381bf6' for node 'Docker builder image-0000i1zamejp6'.


```

**This all worked prior to Wednesday.** Could this be related to the Java Docker API update?

**Comment by roman-vynar** [comment] 2020-04-03 13:20
Probably the same as described here https://github.com/jenkinsci/docker-plugin/issues/782#issuecomment-608300466

**Comment by ericcitaire** [comment] 2020-04-03 13:25
This seems to be authentication related. That's probably why I didn't see it. I'll to reproduce this.

**Comment by FeynmanFan** [comment] 2020-04-03 16:47
A little more info - repro steps from above again:

1. Make repo private
2. Set auth stuff in cloud config for agent
3. Queue build

Build never completes, agent is never pulled. If I perform the following steps:

1. Make repo public
2. Remove creds from cloud config for agent
3. Queue build

It STILL fails to pull the agent. If I **restart** and queue a build, Jenkins pulls the agent and the build succeeds. Don't know if that helps. Seems like some sort of credential / agent caching going on that only a restart clears.

**Comment by pjdarton** [comment] 2020-04-03 16:52
@FeynmanFan Yes, this is almost certainly related to the recent turmoil w.r.t. docker-java-api-plugin.
While #782 was a quickly fixed (because Eric's work on #777 paved the way for a fast reaction), this issue slipped through the net - I don't the code even has a unit test for accessing a non-public registry (PRs welcome...).

@ericcitaire If you can find a fix for this, it'd be much appreciated.  I'll keep an eye out for any PRs etc.
It might be worth also checking if it's a known bug in the docker-java code that's fixed in a later release; if so, it might be necessary to bump to an even later version ... but if we do, I'd suggest that we coordinate releases.

Both: FYI there is caching of the "DockerAPI" object; there's "clever code" that does that...  You'll see mention in the logs (not sure what logging level) about it caching and/or discarding those objects.
One thing you could try is, after queuing the build and letting it fail a while, then cancel the build and wait a while (30min?) before re-queuing the build.  You should see log messages about it dropping the API object from the cache and re-creating it.
...and I think you might even be able to force a new API by changing the read-timeout value in manage-jenkins -> configure system
If fetching a new API object gives the same curative effect as a Jenkins restart then we'll know it's down to the caching, and that'll help narrow our search...

**Comment by ericcitaire** [comment] 2020-04-04 14:39
It seems this is caused by a Guava class not found in the Jenkins provided Guava version (v11).

In [`com.github.dockerjava.core.exec.AbstrDockerCmdExec` line 45](https://github.com/docker-java/docker-java/blob/3.1.5/src/main/java/com/github/dockerjava/core/exec/AbstrDockerCmdExec.java#L45), `com.google.common.io.BaseEncoding` is used. This class didn't exist in Guava 11 and was introduced in Guava 14. docker-java 3.1.5 depends on Guava 19.

Can someone try to install [docker-java-api-3.1.5-rc22.37e46fe5f94d.hpi](https://ci.jenkins.io/job/Plugins/job/docker-java-api-plugin/job/PR-7/1/artifact/org/jenkins-ci/plugins/docker-java-api/3.1.5-rc22.37e46fe5f94d/docker-java-api-3.1.5-rc22.37e46fe5f94d.hpi) and test it with the same conditions? @FeynmanFan @roman-vynar

**Comment by FeynmanFan** [comment] 2020-04-04 17:30
I can confirm that the 3.1.5.2 update fixes the problem with no obvious regression elsewhere.

**Comment by roman-vynar** [comment] 2020-04-06 07:37
Fixed now, thanks!

Upgraded: Docker 1.1.9 >1.2.0, Docker API 3.0.14 > 3.1.5.2

**Closed** 2020-04-06 16:24 UTC

**Comment by pjdarton** [comment] 2020-04-06 16:38
I'll second that: @ericcitaire Thank you for fixing this.
