### ISSUE TITLE
0.9-beta-1. Work for you?

### ISSUE THREAD

**Issue by magnayn** [jenkinsci/docker-plugin#177] opened 2015-03-20 09:03 UTC
Please comment here if it does or does not.

This should be available in the jenkins 'pre-release' / beta channels.

Given the time elapsed, unless it's a blocking issue (I.E: *worse* than 0.8.x), we should probably aim to release and mop up anything minor in a 0.9.1.

**Comment by lexandro** [comment] 2015-03-20 10:25
I checked out and tried to build, but I have a build failure. Is there any wiki page here with a build description to see what I did wrong?

**Comment by KostyaSha** [comment] 2015-03-20 10:26
@lexandro #178 next time post logs.

**Comment by lexandro** [comment] 2015-03-20 10:28
You're right. Sorry:


[INFO] Scanning for projects...
[WARNING] The POM for org.jenkins-ci.tools:maven-hpi-plugin:jar:1.106 is missing, no dependency information available
[WARNING] Failed to build parent project for com.nirima:docker-plugin-parent:pom:0.9-beta1
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] Docker-java shaded jar for jenkins plugin
[INFO] Docker plugin parent pom
[INFO] Docker plugin
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Docker-java shaded jar for jenkins plugin 0.9-beta1
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.nirima.docker-java:docker-java:jar:1.0.1-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Docker-java shaded jar for jenkins plugin .......... FAILURE [  0.065 s]
[INFO] Docker plugin parent pom ........................... SKIPPED
[INFO] Docker plugin ...................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.726 s
[INFO] Finished at: 2015-03-20T11:27:33+01:00
[INFO] Final Memory: 11M/244M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project docker-java-shaded: Could not resolve dependencies for project com.nirima:docker-java-shaded:jar:0.9-beta1: Could not find artifact com.nirima.docker-java:docker-java:jar:1.0.1-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by KostyaSha** [comment] 2015-03-20 10:34
@lexandro please don't duplicate issues https://issues.jenkins-ci.org/browse/JENKINS-26517 and #178 
This caused because @magnayn is not trying to do clean builds and working in his trashed development environment with patched libraries. Hopefully he published library and seems now we need update repositories configuration for successful artifacts resolution. This should be done @magnayn to ensure that build picks right version that he expect to be in build.

**Comment by magnayn** [comment] 2015-03-20 11:00
The library has *always* been published (and it's also in github) - just
that because maven is so wonderful, you get no warning that something that
builds locally won't resolve without manually zapping your ~/.m2/repository
directory.

**Comment by KostyaSha** [comment] 2015-03-20 11:03
@magnayn try read mvn --help at least. You can easily define temporary maven repository locally.
Just try to run 'mvn -Dmaven.repo.local=./temp package`

**Comment by tjamet** [comment] 2015-03-22 13:15
I've troubles with the Volumes option, it looks like commit b1377e7 dropped it with
| | | -        if (volumes.length > 0)
| | | -            hostConfig.setBinds(volumes);
| | | +        // ?
| | | +        //if (volumes.length > 0)
| | | +        //    hostConfig.with VolumesFrom (volumes);

I've tried to fix it with
for( String volume:volumes){
    hostConfig.withBinds(new Bind(volume.split(":",1)[0],new Volume(volume.split(":",1)[1]);
}
But did not get it working for now

**Comment by KostyaSha** [comment] 2015-03-22 13:20
@tjamet please open issue and describe how i can reproduce

**Comment by KostyaSha** [comment] 2015-03-22 17:39
I still see classloading errors for "Test connection" button. Round one in my fighting with dependencies seems failed.

**Comment by KostyaSha** [comment] 2015-03-22 18:11
Seems jDocker library requires 4.3 httpcore https://hc.apache.org/httpcomponents-core-ga/httpcore/apidocs/org/apache/http/config/Lookup.html but it's pom define 4.2 httpclient. That's why docker-plugin pins httpclient/core...

**Comment by KostyaSha** [comment] 2015-03-22 22:14
Upstream accepted dependency fix, waiting new -SNAPSHOT to continue testing ;)

**Comment by KostyaSha** [comment] 2015-03-22 22:42
@magnayn how many patches are on top of upstream docker-java?

**Comment by magnayn** [comment] 2015-03-23 09:35
The only thing that you might need is this:
https://github.com/magnayn/docker-java/commit/497ad156cac164d5792db83dc62097c38cf75c7b

Though it looks like the API has been adjusted, so we could change the
plugin's usage to something like

DockerClientBuilder.getInstance().withDockerCmdExecFactory( new
DockerCmdExecFactoryImpl() ).build();

And move back to upstream

**Comment by KostyaSha** [comment] 2015-03-23 11:31
@magnayn could you do it?

**Comment by michaelheyvaert** [comment] 2015-03-26 09:27
I'm currently blocked on this issue: https://github.com/jenkinsci/docker-plugin/issues/106

**Comment by magnayn** [comment] 2015-03-26 09:59
Right, but that's not new to beta-1, it's always used ssh -D.

**Comment by michaelheyvaert** [comment] 2015-03-26 10:31
I didn't had this issue with previous versions, I don't have the ssh -D issue (my slaves use the default), so it seems that this cleanup issue can be triggered by other conditions

**Comment by KostyaSha** [comment] 2015-03-26 18:10
Seems @magnayn moved to mainline library and didn't notify :(. I will try to work full-time on this plugin at weekend. Any help with testing and debugging will be appreciated by directly pinging me on IRC channel. @thomassuckow will you have some time?

**Comment by KostyaSha** [comment] 2015-03-27 00:30
Round 2 in deps and i pom become clear, still testing. My work in #187 Also fixed 'test connection' button.
@magnayn for what used services file in META-INF? As i see it exist in library, do we need to have it in plugin?

**Comment by KostyaSha** [comment] 2015-03-28 04:17
Why not inherit DockerTemplate->DockerTemplateBase->Slave ? This will exclude redundant fields/methods.

**Comment by KostyaSha** [comment] 2015-03-30 18:50
Still continue overviewing design, for strategies i think it makes sense provide 2 available strategies and configurable number of executors.

**Comment by magnayn** [comment] 2015-03-31 08:52
The META-INF was how docker-java decides on which implemetation to use -
but isn't needed now (and didn't work anyway because of classloader
nonsense) since we force it.

**Comment by KostyaSha** [comment] 2015-04-23 21:48
I plan build new beta on weekend.

**Comment by KostyaSha** [comment] 2015-04-23 23:02
Current master should resolve many issues.. will build earlier...

**Comment by KostyaSha** [comment] 2015-04-23 23:33
Done, Uploaded: http://maven.jenkins-ci.org:8081/content/repositories/releases/com/nirima/docker-plugin/0.9.0-beta2/docker-plugin-0.9.0-beta2.hpi (14299 KB at 53.2 KB/sec)

**Comment by KostyaSha** [comment] 2015-04-23 23:50
Opened #210 , closing this.

**Closed by KostyaSha** 2015-04-23 23:50 UTC
Labels: beta-test
