### ISSUE TITLE
Containers sometimes don't get removed after job is done

### ISSUE THREAD

**Issue by farahfa** [jenkinsci/docker-plugin#401] opened 2016-06-16 20:42 UTC
Hello,

From time to time, I notice that there are a lot of containers that aren't removed after the job is done, is there an explanation as to why that happens? Is it a bug or am I missing something? When I do docker rm $(docker ps -a -q) and remove the containers and then run a bunch of jobs, then it works as expected.

Fadi

**Comment by HadesArchitect** [comment] 2016-06-16 20:51
Hi,

which exactly containers aren't removed? Slaves? Can you show _docker ps_?

**Comment by KostyaSha** [comment] 2016-06-16 20:56
There are a lot of bugs in docker-plugin around provisioning :)

**Comment by HadesArchitect** [comment] 2016-06-16 21:11
For sure :)

But I clearly see a great future in this plugin. Docker popularity &, therefore, community will grow!

**Comment by HadesArchitect** [comment] 2016-06-16 21:12
I've asked for details because I don't have any troubles with containers remaining... Except my own containers which were spawned during job execution.

**Comment by KostyaSha** [comment] 2016-06-17 22:57
> Except my own containers which were spawned during job execution.

That fixable with cleanup mechanisms. 

> But I clearly see a great future in this plugin.

It had future until CB employees started rewriting their own plugins with the same functionality (even i was forced to rewrote it).

> From time to time, I notice that there are a lot of containers that aren't removed after the job is done, is there an explanation as to why that happens? Is it a bug or am I missing something?

That can be everything. When i was maintainer here i placed https://github.com/jenkinsci/docker-plugin/blob/master/CONTRIBUTING.md , but nobody providing well formed issues with use cases and logs. If i right remember it should be not required to do manual clean-ups because in code i made automatic cleanups after timeout (or in other plugin... but should be in this, i remember that deal with such cases).

**Comment by farahfa** [comment] 2016-06-23 18:47
@HadesArchitect, Sorry for not replying sooner. But yes I was referring to Slaves still showing up when I do docker ps -a (they wouldn't be running but they're not completely removed which ends up taking space). But this happens randomly and I cannot reproduce the problem anytime I want and right now it's working just fine, but I'm sure in the future this will happen again.

**Comment by jommgoncalves** [comment] 2016-08-19 14:54
I have the same problem. @farahfa How you solve this problem?

**Comment by farahfa** [comment] 2016-08-19 15:10
Unfortunately, I haven't solved the issue.. I have a cronjob that runs `docker rm -f $(docker ps -a -q)` at a time where I know no-one is going to be using Jenkins.. Which removes all containers..

Also, not sure if this helps or not but I've updated linux-image, headers & image-extras to latest...

**Comment by jommgoncalves** [comment] 2016-08-19 15:16
@farahfa This workaround is dangerous :\ 
In my case, I have containers that run every time.
Do you have another suggestion for me?

Thanks a lot,

**Comment by farahfa** [comment] 2016-08-19 15:42
I am sorry but I do not have a better suggestion for you.  :/

**Comment by eaglerainbow** [comment] 2016-08-19 20:22
I can confirm that still with 0.16.1 I also experience the same kind of issue: "Sometimes" containers are not removed properly in all different kind of variants:
* Containers are stopped with exit code 0, but it is not removed.
* Containers are still running, but the slave agent has already been stopped.

I observed this behaviour both on "low load situations" as well as on "high load situations". However, they tend to appear in groups, that is to say that I often see between three to six containers which suffer from the same issue. They all were created around the same time (as my load typically always takes the same amount of time, it oculd also be that they are attempted to be pruned around the same point in time). 
Unfortunately, all these cases always happened in my night time (and the logs are so huge due to the amount of jobs executed), that I could not "nail anything down".
For me, the stopped containers are just "ugly", but those containers which are orphaned are critical, as they count both for the instance limit and the container cap.

**Comment by jommgoncalves** [comment] 2016-08-19 21:27
@eaglerainbow Your experience is similar to mine.

I found this problem because I had the container gap with a low value and one of my pipelines stopped every day :\

For now, I increased the container gap and I will continue to monitorize this problem in order to fix it as soon as possible. If I can fix it, I give news :)

**Comment by eaglerainbow** [comment] 2016-08-19 23:17
I briefly implemented a watchdog to allow a better analysis of this issue. As depicted in the commit message, we can also think about "automatically cleaning up the mess", which the watchdog detected.

I'd be eager to hear your thoughts about this approach.

**Comment by jommgoncalves** [comment] 2016-08-22 18:15
For me, this approach doesn't resolve this issue, it is only to mitigate it. I really would like to understand why containers sometimes don't get removed after job is done.

Btw, in my specific case, I have a job that it is created by Jenkins and then executes 
`docker run -d -u ${user} -p ${port}:${port} -v ${volume_host}:${volume_container} ${image} sh -c 'command'`
With this approach, this job will be removed if I understood well or not?

For analysis, I would like to suggest add more output in logs when a container is created and removed. There may be a pattern.

**Comment by eaglerainbow** [comment] 2016-08-22 18:42
> With this approach, this job will be removed if I understood well or not?

No. The job scans only for those containers, which have been tagged with a special label. This label contains a unique identifier of the docker-plugin (including the JenkinsId). If the label is missing (which is the case for your command line), then the watchdog does not care about this container (NB: in your case, your containers are counted by the docker-plugin into the container cap! That's another fact, which causes quite some headache for me -- see also https://github.com/jenkinsci/docker-plugin/pull/409 ).

Concerning the question on the root cause: I don't think that the issue is related to _creating_ it, but the error most likely is to be found when removing it. For instance, I often see error messages indicating that the communication channel to the slave was closed abruptly. I could imagine that the Jenkins core then doesn't inform the DockerCloud instance anymore (and thus there is no removal request sent to the docker host). That thought also originally was my idea for the watchdog: It shall support us in determining the docker containers which were not removed and write them to the log. Then we can correlate the container's ID with what has happened to the container before. Perhaps we then can make out some patterns.

**Comment by jommgoncalves** [comment] 2016-08-22 19:42
> For instance, I often see error messages indicating that the communication channel to the slave was closed abruptly. I could imagine that the Jenkins core then doesn't inform the DockerCloud instance anymore (and thus there is no removal request sent to the docker host).

Maybe it is the cause for this issue. I've remembered it too.

> It shall support us in determining the docker containers which were not removed and write them to the log. Then we can correlate the container's ID with what has happened to the container before. Perhaps we then can make out some patterns.

I understand your approach totally now. Let's to do this :)

**Comment by KostyaSha** [comment] 2016-08-22 21:18
> For instance, I often see error messages indicating that the communication channel to the slave was closed abruptly.

You are on the long way of bug wrangling in jenkins cloud/remoting api  :)

**Comment by eaglerainbow** [comment] 2016-08-23 20:22
@KostyaSha: You sound as if you knew more :)  Is there a shortcut for our debugging?

**Comment by jommgoncalves** [comment] 2016-08-26 10:58
Hi,

> Case:
We are making some tests to improve the performance of one of our servers. I started one job and after some seconds/minutes I decide to cancel it.

> What's happened?
Docker container continues working on the machine.

> Logs:
`[08/26/16 10:21:59] SSH Launch of XXXX-40d4bcff220c on XXXX completed in 6,466 ms
Aug 26, 2016 10:25:15 AM hudson.model.AsyncPeriodicWork$1 run
INFO: Started JClouds slave cleanup
Aug 26, 2016 10:25:15 AM hudson.model.AsyncPeriodicWork$1 run
INFO: Finished JClouds slave cleanup. 0 ms
Aug 26, 2016 10:26:01 AM hudson.model.Run execute
INFO: xxxx_job #151 aborted
java.lang.InterruptedException
       	at java.lang.Object.wait(Native Method)
       	at hudson.remoting.Request.call(Request.java:147)
       	at hudson.remoting.Channel.call(Channel.java:796)
       	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:252)
       	at com.sun.proxy.$Proxy66.join(Unknown Source)
       	at hudson.Launcher$RemoteLauncher$ProcImpl.join(Launcher.java:991)
       	at hudson.tasks.CommandInterpreter.join(CommandInterpreter.java:135)
       	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:95)
       	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:64)
       	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
       	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
       	at hudson.model.Build$BuildExecution.build(Build.java:205)
       	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
       	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
       	at hudson.model.Run.execute(Run.java:1720)
       	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
       	at hudson.model.ResourceController.execute(ResourceController.java:98)
       	at hudson.model.Executor.run(Executor.java:404)
Aug 26, 2016 10:26:01 AM com.nirima.jenkins.plugins.docker.builder.DockerBuilderControlOptionStopAll execute
INFO: Stopping all containers
Aug 26, 2016 10:26:01 AM com.nirima.jenkins.plugins.docker.DockerSlave _terminate
INFO: Disconnected computer
Aug 26, 2016 10:27:01 AM com.nirima.jenkins.plugins.docker.DockerSlave _terminate
SEVERE: Failed to stop instance 40d4bcff220c4b13641948eee2789b4f937a0cfdd3d2a253b8fad804ce59bb2b for slave XXXX-40d4bcff220c due to exception
Aug 26, 2016 10:27:01 AM com.nirima.jenkins.plugins.docker.DockerSlave _terminate
INFO: Shutdowned slave for 40d4bcff220c4b13641948eee2789b4f937a0cfdd3d2a253b8fad804ce59bb2b
Aug 26, 2016 10:27:01 AM com.nirima.jenkins.plugins.docker.DockerSlave _terminate
SEVERE: Failed to remove instance 40d4bcff220c4b13641948eee2789b4f937a0cfdd3d2a253b8fad804ce59bb2b for slave XXXX-40d4bcff220c due to exception: You cannot remove a running container 40d4bcff220c4b13641948eee2789b4f937a0cfdd3d2a253b8fad804ce59bb2b. Stop the container before attempting removal or use -f
Aug 26, 2016 10:27:01 AM hudson.slaves.SlaveComputer tryReconnect
INFO: Attempting to reconnect XXXX-40d4bcff220c
[08/26/16 10:27:01] SSH Launch of unknown on XXXX failed in 468 ms`

Cheers,

**Comment by eaglerainbow** [comment] 2016-08-31 20:57
@jommgoncalves: I would assume that the root cause for the issue is to be found here: 

> SEVERE: Failed to stop instance 40d4bcff220c4b13641948eee2789b4f937a0cfdd3d2a253b8fad804ce59bb2b for slave XXXX-40d4bcff220c due to exception

We'll have to check if we can reproduce this also outside of your environment. If we then get additional information out of the exception which was thrown, then this would help to track this leak.

**Comment by KostyaSha** [comment] 2016-08-31 21:26
welcome to synchronisation hell of jenkins cloud api :)

**Comment by eaglerainbow** [comment] 2016-09-02 20:15
@jommgoncalves: I played around with your case, but could not reproduce it.
Which plugin version are you using? Which docker version? Any experimental settings for your template? Anything worthwhile mentioning in the system configuration?

**Comment by eaglerainbow** [comment] 2016-09-02 20:32
@jommgoncalves: Though I was not able to reproduce it, I prepared a commit suggesting to add additional debug output to allow proper backtracking in case the issue reappears. Especially, I hope that by this we will get a stack trace indicating why stopping the instance failed.

**Comment by pjdarton** [comment] 2018-08-30 14:39
Fixed by #658

**Closed by pjdarton** 2018-08-30 14:39 UTC
Labels: bug

**Comment by Abubakar22** [comment] 2018-11-01 20:28
> @eaglerainbow Your experience is similar to mine.
> 
> I found this problem because I had the container gap with a low value and one of my pipelines stopped every day :\
> 
> For now, I increased the container gap and I will continue to monitorize this problem in order to fix it as soon as possible. If I can fix it, I give news 

I am facing the same issue, how and where do you set the container gap? 
I am using Docker plugin version 1.0.4 and Jenkins 2.121.3

**Comment by emnabarred** [comment] 2024-08-02 12:18
Having the same issue. I see there is a Jira bug on the topic https://issues.jenkins.io/browse/JENKINS-67089

**Comment by pjdarton** [comment] 2024-08-02 19:27
@emnabarred That Jira issue is for a different plugin, not this one.
See [README.md](https://github.com/jenkinsci/docker-plugin/blob/master/README.md#see-also) for some more details.
