### ISSUE TITLE
jenkins server and slaves are running as containers in the same host

### ISSUE THREAD

**Issue by henrysher** [jenkinsci/docker-plugin#219] opened 2015-05-12 00:31 UTC
Hi, I just have the usage like this, no idea whether you will support in docker-plugin:
1. jenkins server is running inside a docker container (A)
2. jenkins slave created and provisioned by docker-plugin is also running inside a docker container (B)
3. both container A and container B is running in the same host

The problem is that:
1. docker-plugin (container A) needs a API url (http://172.17.42.1:4243), which means I have to open the port 4243 in the firewall for all the incoming traffic
2. docker-plugin (container A) will create a slave (container B) with a host port (32378, etc.) bind, and jenkins server will communicate with this slave via SSH in this host port (172.17.42.1:32378), but failed due to the firewall reason.

So do you have any suggestion/solution on this kind of requirement?
one solution i could see, but not sure whether available for the scenario of jenkins server and slaves running across mulitple hosts:
1. docker-plugin takes the internal ip address of a slave (container B) and jenkins server communicates with the slave via ssh in port 22.

Do you have any concern on this solution?

**Comment by magnayn** [comment] 2015-05-12 10:57
It doesn't do this currently, but you might be able to make it.

The inspect API can give you the IP address that the container has. You'd
have to be careful that the container/IP that was started was the actual
one you're talking to - possibly via container name as well.

I.E: it's not possible to know just with the IP address that (say)
172.16.12.44:22 is the container that you just started - because a
completely different docker host might have picked the same subnet and have
a host - but if you check the hostname started that's probably sufficient.

**Comment by KostyaSha** [comment] 2015-05-12 11:34
Systemd-machined has integration with NSS and some other protocols that allows accessing containers. This probably a question to docker whether it can provide well accessible hostnames.

**Comment by justnom** [comment] 2015-05-12 18:27
I have my Jenkins master running inside a Docker container (using [official image](https://registry.hub.docker.com/_/jenkins/)).

* Set the Docker daemon to bind to the `docker0` interface. Example:
```
DOCKER_OPTS="-H tcp://172.17.42.1:4243 -H unix:///var/run/docker.sock"
```
* Change the `Configure System > Cloud > Docker > Docker URL` Jenkins setting to `http://172.17.42.1:4243`
* Check the `Configure System > Cloud > Docker > Docker Template > Bind all declared ports` setting
* Make sure that you have `EXPOSE 22` in your Dockerfile

Hope this helps

**Comment by henrysher** [comment] 2015-05-13 05:17
@justnom i have tried your way, but failed still relevant to the firewall setting. 
```
May 13, 2015 5:05:06 AM com.nirima.jenkins.plugins.docker.DockerComputerLauncher getSSHLauncher
INFO: Creating slave SSH launcher for 172.17.42.1:32773
May 13, 2015 5:05:36 AM hudson.slaves.CloudRetentionStrategy$1 run
INFO: Disconnecting 81e9158d54db@docker
[05/13/15 05:05:39] SSH Launch of 14fe61cae14a@docker on 172.17.42.1 failed in 1,009 ms
[05/13/15 05:05:40] SSH Launch of 14fe61cae14a@docker on 172.17.42.1 failed in 1,005 ms
```

**Comment by justnom** [comment] 2015-05-13 10:50
@henrysher To proof out that it indeed is a firewall issue - could you please disable the firewall and test the connection again?

If it still doesn't work - on your Docker host machine - run `docker ps` and make sure that your Jenkins slave container is running and listening on `0.0.0.0` - the port doesn't matter as it will be picked up by the Docker plugin.

**Comment by looztra** [comment] 2015-08-18 13:57
@justnom is your setup working after a reboot?

I had bad experiments with the same settings after reboot because it is the docker daemon that creates the bridge ip hence it cannot start with your setup because it is facing a "chicken and egg" problem.

Note: this issue is a duplicate of #206 (cc @fcoelho)

**Comment by justnom** [comment] 2015-08-19 19:54
@looztra 

My system does indeed still work after a reboot. I am running it on Ubuntu 14.04.

Another solution for you:
1. Install `socat` in your Jenkins master Docker container.
2. Mount `/var/run/docker.sock` in the Jenkins master container.
3. Run `socat unix:///var/run/docker.sock tcp4-listen:4243` inside the master container (either before the Jenkins is started, or manually with `docker exec`).
4. Now you can use `127.0.0.1:4243` to connect to Docker in the plugin settings.

Hope this works :)

**Comment by ndeloof** [comment] 2017-10-10 12:59
For such infrastructure the simplest option use to rely on JNLP launcher, so new agent don't have to expose some additional network ports.
You also can give attached launcher in 0.17 a try

**Closed by ndeloof** 2017-10-10 12:59 UTC
Labels: connect
