### ISSUE TITLE
NullPointerException trying to use the build step "Build / Publish Docker Containers"

### ISSUE THREAD

**Issue by paolosystemx** [jenkinsci/docker-plugin#254] opened 2015-06-24 13:36 UTC
How to reproduce : 
1/ Clone the docker-plugin git repo at github
2/ Install and setup a docker host locally (DOCKER_OPTS="-H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock")
3/ Debug the plugin locally using maven:
cd <...>/docker-plugin
export MAVEN_OPTS="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,address=8000,suspend=n"
mvn hpi:run
4/ Setup a Docker Cloud:
Name: Docker
Docker URL: http://127.0.0.1:4243
5/ Create a new jenkins "free-style software project":
- Clone some repo with a Dockerfile at root level (named docker.git in the example below)
- Add a single build step of type "Build / Publish Docker Containers" with "Directory for Dockerfile"=.
6/ Run a build manually.

The build fails with the follpowing log:

 > Started by user anonymous
 > Building in workspace /home/paolo/dev/github/docker-plugin/docker-plugin/work/jobs/docker/workspace
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url git@gitserver:docker.git # timeout=10
Fetching upstream changes from git@gitserver:docker.git
 > git --version # timeout=10
 > git -c core.askpass=true fetch --tags --progress git@gitserver:docker.git +refs/heads/*:refs/remotes/origin/*
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
Checking out Revision fd2109bf2dc246e9bd927f8f201896914d2557b9 (refs/remotes/origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f fd2109bf2dc246e9bd927f8f201896914d2557b9
 > git rev-list fd2109bf2dc246e9bd927f8f201896914d2557b9 # timeout=10
Docker Build
Docker Build : build with tag docker at path /home/paolo/dev/github/docker-plugin/docker-plugin/work/jobs/docker/workspace
FATAL: null
java.lang.NullPointerException
	at com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher$Run$1.invoke(DockerBuilderPublisher.java:142)
	at com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher$Run$1.invoke(DockerBuilderPublisher.java:137)
	at hudson.FilePath.act(FilePath.java:920)
	at hudson.FilePath.act(FilePath.java:893)
	at com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher$Run.buildImage(DockerBuilderPublisher.java:137)
	at com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher$Run.run(DockerBuilderPublisher.java:87)
	at com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher.perform(DockerBuilderPublisher.java:174)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:756)
	at hudson.model.Build$BuildExecution.build(Build.java:198)
	at hudson.model.Build$BuildExecution.doRun(Build.java:159)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
	at hudson.model.Run.execute(Run.java:1706)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:88)
	at hudson.model.Executor.run(Executor.java:232)

**Comment by igorbljahhin** [comment] 2015-06-25 13:24
Same issue here.

**Comment by KostyaSha** [comment] 2015-06-25 13:43
Hi, i plan check and review publisher after #234 . Sorry for delay (my laptop was/is broken).

**Comment by paolosystemx** [comment] 2015-06-25 15:41
Thank you very much.
In the meantime, could you provide info on what this build step is really meant to do?
My intent is to build an image and use it as a template for the slave which actually runs the build later.
Is that what it's suposed to do?
Thank you in adavnce for your help.

**Comment by igorbljahhin** [comment] 2015-06-26 07:44
After reading the source code of https://github.com/jenkinsci/docker-plugin/blob/master/docker-plugin/src/main/java/com/nirima/jenkins/plugins/docker/builder/DockerBuilderPublisher.java, I guess mine NullPointerException happens because getDockerClient() method returns null. What is "docker slave" in the terms of the plugin?

**Comment by paolosystemx** [comment] 2015-06-29 08:30
Hi @igorbljahhin , I did not find anything in the doc about this feature, did you?

**Comment by hcguersoy** [comment] 2015-07-15 13:53
Hi,

the same issue here except that I want to build the docker image in a docker slave (a DinD Slave image is used here):

```
Docker Build
Docker Build : build with tag 192.168.56.13:5000/mysql-base:04-18 at path /var/lib/jenkins/jobs/mysql_base/workspace
ERROR: Build step failed with exception
java.lang.NullPointerException
	at com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher$Run$1.invoke(DockerBuilderPublisher.java:142)
	at com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher$Run$1.invoke(DockerBuilderPublisher.java:137)
	at hudson.FilePath.act(FilePath.java:989)
	at hudson.FilePath.act(FilePath.java:967)
	at com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher$Run.buildImage(DockerBuilderPublisher.java:137)
	at com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher$Run.run(DockerBuilderPublisher.java:87)
	at com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher.perform(DockerBuilderPublisher.java:174)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:761)
	at hudson.model.Build$BuildExecution.build(Build.java:203)
	at hudson.model.Build$BuildExecution.doRun(Build.java:160)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:536)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:374)
Build step 'Build / Publish Docker Containers' marked build as failure
```

Maybe this is related to https://github.com/tehranian/dind-jenkins-slave/issues/4 ?
In this case you are not able to use docker in a jenkins shell executor. 

And maybe this one https://github.com/jenkinsci/docker-plugin/issues/213
This is a issue which I've reported some time ago but not managed yet to provide a test for it.

**Comment by magnayn** [comment] 2015-07-15 14:02
This smells like #267 which is fixed in master.

**Comment by KostyaSha** [comment] 2015-07-15 21:56
I plan do hotfix release soon (hopefully on this weekend)

**Comment by hcguersoy** [comment] 2015-07-17 11:56
Hi,

I can confirm that with a build from master (commit 024877a9d) the Image builds are running fine, again.
For the records, I've changed the same time the version of `docker-java` from 1.3 to 1.4 for #213.

**Closed** 2015-07-20 23:18 UTC
Labels: publisher
