### ISSUE TITLE
run docker build error：Error during callback

### ISSUE THREAD

**Issue by fy976061258** [jenkinsci/docker-plugin#918] opened 2022-10-19 15:22 UTC
### Jenkins and plugins versions report

error log：
ERROR: Build step failed with exception
java.util.NoSuchElementException
	at java.base/java.util.ArrayDeque.removeFirst(ArrayDeque.java:363)
	at java.base/java.util.ArrayDeque.remove(ArrayDeque.java:524)
	at io.netty.handler.stream.ChunkedWriteHandler.doFlush(ChunkedWriteHandler.java:267)
	at io.netty.handler.stream.ChunkedWriteHandler.flush(ChunkedWriteHandler.java:132)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:748)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:740)
	at io.netty.channel.AbstractChannelHandlerContext.access$2200(AbstractChannelHandlerContext.java:59)
	at io.netty.channel.AbstractChannelHandlerContext$Tasks$4.run(AbstractChannelHandlerContext.java:1142)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Build step 'Build / Publish Docker Image' marked build as failure
SSH: Current build result is [FAILURE], not going to run.

system error log：
Oct 19, 2022 3:16:49 PM INFO io.jenkins.docker.client.DockerAPI getOrMakeClient
Cached connection io.jenkins.docker.client.DockerAPI$SharableDockerClient@452dfb97 to DockerClientParameters{dockerUri='tcp://216.250.254.33:2376', credentialsId='null', readTimeoutInMsOrNull=null, connectTimeoutInMsOrNull=60000}
Oct 19, 2022 3:16:49 PM SEVERE com.github.dockerjava.api.async.ResultCallbackTemplate onError
Error during callback
java.util.NoSuchElementException
	at java.base/java.util.ArrayDeque.removeFirst(ArrayDeque.java:363)
	at java.base/java.util.ArrayDeque.remove(ArrayDeque.java:524)
	at io.netty.handler.stream.ChunkedWriteHandler.doFlush(ChunkedWriteHandler.java:267)
	at io.netty.handler.stream.ChunkedWriteHandler.flush(ChunkedWriteHandler.java:132)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:748)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:740)
	at io.netty.channel.AbstractChannelHandlerContext.access$2200(AbstractChannelHandlerContext.java:59)
	at io.netty.channel.AbstractChannelHandlerContext$Tasks$4.run(AbstractChannelHandlerContext.java:1142)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)

### What Operating System are you using (both controller, and any agents involved in the problem)?

centos7 -> docker -> Jenkins

### Reproduction steps

golang build

### Expected Results

success

### Actual Results

error

**Comment by pjdarton** [comment] 2023-01-25 17:07
The error stacktrace here doesn't seem to mention the docker-plugin directly, but it does mention the netty transport layer (a lot), suggesting that the cause of the issue may actually be buried within netty.
...but there's just been a new [release](https://github.com/jenkinsci/docker-plugin/releases/tag/docker-plugin-1.3.0) of the docker-plugin that [replaces the netty transport layer](https://github.com/jenkinsci/docker-plugin/pull/934) so I'd strongly suggest you try that new version - it'll either work now (if so, please close this issue) or fail with a different (hopefully more informative!) message (if so, please describe it here).

**Comment by basil** [comment] 2023-05-26 00:07
The latest releases of `docker-plugin` and `docker-java-api` do not use Netty anymore. Please upgrade to these latest releases. If the problem persists with the latest releases, please file a new issue with steps to reproduce the problem from scratch.

**Closed by basil** 2023-05-26 00:07 UTC
Labels: bug
