### ISSUE TITLE
Registry Credentials Not Used To Pull (build step)

### ISSUE THREAD

**Issue by jbnance** [jenkinsci/docker-plugin#589] opened 2017-12-15 16:00 UTC
Jobs that are configured to use a "Build / Publish Docker Image" build step with registry credentials do not appear to be using the credentials when pulling the parent image (the "FROM" in the Dockerfile).

Plugin version: 1.1.1
Jenkins version: 2.89.2
Docker version: 1.13.1
Docker API Jenkins plugin version: 3.0.14

Console output says:

```
15:43:06 Docker Build
15:43:06 Docker Build: building image at path /var/lib/jenkins/workspace/docker-image-build-step/wf-httpd-base
15:43:06 Step 1/11 : FROM my.private.registry:5443/wf/wf-os-base:latest
15:43:06 
15:43:06 ERROR: Build step failed with exception
15:43:06 com.github.dockerjava.api.exception.DockerClientException: Could not build image: unauthorized: authentication required
15:43:06 	at com.github.dockerjava.core.command.BuildImageResultCallback.getImageId(BuildImageResultCallback.java:79)
15:43:06 	at com.github.dockerjava.core.command.BuildImageResultCallback.awaitImageId(BuildImageResultCallback.java:51)
15:43:06 	at com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher$Run.buildImage(DockerBuilderPublisher.java:353)
15:43:06 	at com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher$Run.run(DockerBuilderPublisher.java:286)
15:43:06 	at com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher.perform(DockerBuilderPublisher.java:423)
15:43:06 	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
15:43:06 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
15:43:06 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
15:43:06 	at hudson.model.Build$BuildExecution.build(Build.java:206)
15:43:06 	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
15:43:06 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
15:43:06 	at hudson.model.Run.execute(Run.java:1724)
15:43:06 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
15:43:06 	at hudson.model.ResourceController.execute(ResourceController.java:97)
15:43:06 	at hudson.model.Executor.run(Executor.java:421)
15:43:06 Build step 'Build / Publish Docker Image' marked build as failure
```

I'm not sure if the plugin is passing the credentials to the API plugin or not.  If it is and the issue is really withe API plugin please let me know and I'll open the issue over there.

**Comment by jbnance** [comment] 2017-12-15 18:00
It appears that this issue may be related to the instantiation of `DockerRegistryEndpoint` in `DockerBuilderPublisher.java`:

```
public DockerRegistryEndpoint getFromRegistry() {
    if (fromRegistry == null) {
        fromRegistry = new DockerRegistryEndpoint(null, pullCredentialsId);
    }
    return fromRegistry;
}
```

If the first argument is `null` the URL is set to `https://index.docker.io/v1/`.  There is a `fromImageName` method in `DockerRegistryEndpoint` which can be used to parse the argument to "FROM" (registry:port/namespace/image:tag) in the Dockerfile and return a `DockerRegistryEndpoint` with the correct URL.

**Comment by ndeloof** [comment] 2017-12-15 19:55
good catch. But I guess this won't be enough to cover multi-staged docker builds.

**Comment by ndeloof** [comment] 2017-12-15 20:09
can you maybe prepare a pull-request with a fix for this ?
would need to parse Dockerfile for (all) `FROM *` strings and configure registry credentials accordingly

**Comment by ndeloof** [comment] 2017-12-15 20:12
hum, registry URL is actually not used, see https://github.com/jenkinsci/docker-plugin/blob/master/src/main/java/com/nirima/jenkins/plugins/docker/builder/DockerBuilderPublisher.java#L330

**Comment by jbnance** [comment] 2017-12-18 14:38
I have 0 Java experience so I apologize for any newbie-ness.  It looks like the block starting on line 331 means to add the registry authentication stuffs (https://github.com/jenkinsci/docker-plugin/blob/master/src/main/java/com/nirima/jenkins/plugins/docker/builder/DockerBuilderPublisher.java#L331):

```
if (pullRegistry != null && pullRegistry.getCredentialsId() != null) {
    auths.addConfig(DockerCloud.getAuthConfig(pullRegistry, run.getParent().getParent()));
}
```

Though, assuming that is correct, I don't think that using the `DockerCloud` object is the correct approach given that the credentials for the `pullRegistry` can be supplied in the job config itself (and likely often have little to do with the `DockerCloud` configuration).

Do you agree?  If so, do you think it would be appropriate to update the declaration of `getFromRegistry()` to support passing in an optional URL?  I'm not sure where the best place would be to parse the "FROM" tag.

**Comment by ndeloof** [comment] 2017-12-18 15:00
`DockerCloud.getAuthConfig` is utility method, could be owned by some `DockerUtil` class, unrelated to the Cloud instance.
As I said, `auths.addConfig` directly consumes authentication, it doesn't rely on the registry URL (exactly like the docker API does). Registry to credentials mapping is a pure docker CLI feature, modelled by docker-commons in `DockerRegistryEndpoint`, but that doesn't apply to direct API usage as docker-plugin does.

**Comment by ndeloof** [comment] 2017-12-20 09:30
Tried to reproduce, but I get the expected credentials set to pull a private image from dockerhub.

**Comment by ndeloof** [comment] 2017-12-20 10:10
ok, so the /build API do expect the client to send all required Auths, with ServerAddress set. As I'm using dockerhub (which is default ServerAddress) I didn't caught this.

**Closed** 2017-12-20 10:10 UTC

**Comment by pteichner** [comment] 2017-12-20 10:31
So when the from specifies a custom registry in the Dockerfile it doesn't work?

**Comment by ndeloof** [comment] 2017-12-20 10:34
yes indeed. fixed in https://github.com/jenkinsci/docker-plugin/commit/9109ed38359aaeca0850f42cb24527076c95908a
a nicer solution would be to parse Dockerfile and detect `FROM` command, but would make this a crazy beast (assuming a trivial replacement for this builder is to use plain docker CLI)

**Comment by pteichner** [comment] 2017-12-20 14:20
When is the next release due to go out?

**Comment by ndeloof** [comment] 2017-12-20 14:22
no short term plan, as I'll be on vacation I won't run a release this week - I couldn't fix urgent regressions if something wrong is discovered.
Feel free to test a snapshot build

**Comment by jbnance** [comment] 2017-12-20 16:03
Thank you very much for this

**Comment by alexindigo** [comment] 2018-02-02 20:32
@ndeloof any news on that from?
Also, we're using `ARG`s within our `FROM` statements ;) (Just to make life more exciting) :)

**Comment by alexindigo** [comment] 2018-09-25 20:17
@ndeloof Looks like it's not meant to work with custom registries – https://github.com/jenkinsci/docker-plugin/blob/15b66d7dabe3298e51544caf136ed732ecdb2b76/src/main/java/com/nirima/jenkins/plugins/docker/DockerTemplateBase.java#L422

It always pass null for the registry url.

Is there a way to use custom registry in Docker Template?

Thank you.
