### ISSUE TITLE
docker-cloud doesn't work with docker hub private images

### ISSUE THREAD

**Issue by lifeofguenter** [jenkinsci/docker-plugin#665] opened 2018-06-27 00:15 UTC
I am trying to use a private repository on hub.docker.com as image/template for launching cloud instances.

Unfortunately I am getting the following error when the docker-plugin is trying to launch an executor:

```
com.github.dockerjava.api.exception.NotFoundException: {"message":"pull access denied for 9jkh/cicd-bare, repository does not exist or may require 'docker login'"}	at 
```

I double verified the credentials, and the user definitely has pull/push rights (verified via cli).

The same docker-image on gitlab.com registry works.

My assumption is that the plugin does not recognise that private repositories can exist on hub.docker.com.

My jenkins is running latest LTS + latest version of this plugin.

**Comment by pjdarton** [comment] 2018-06-27 09:56
I am sure that the plugin does cope with private repositories that require authentication, because that's what I've got at work.  Equally I'm sure that it copes with unauthenticated access to hub.docker.com.
I've not _tried_ authenticated access to hub.docker.com but, then again, I didn't think that the _plugin_ code has any special case handling for hub.docker.com...

It's possible that the underlying `docker-java` library (which this plugin uses) or the shared `docker-commons` plugins might have issues, and hence causing `docker-plugin` to have issues ... but the only thing hinting at special-case stuff is that `docker-java` has code `com.github.dockerjava.api.model.AuthConfig` which has a line `public static final String DEFAULT_SERVER_ADDRESS = "https://index.docker.io/v1/";` and `docker-commons` also defaults to that URL.

One thing to try out, I guess, would be to try putting in the full URL rather than just allowing the default to take effect.

**Comment by lifeofguenter** [comment] 2018-06-27 10:00
@pjdarton 

Yes, this plugin works perfectly (and in general) with private registries (+authed) - I did double verify it with registry.gitlab.com.

But it does not work with authed hub.docker.com (e.g. private repos).

I tried prepending docker.io, e.g. docker.io/9jkh/cicd-bare - same issue.

**Comment by pjdarton** [comment] 2018-06-27 10:07
If you are able to do so ... could you try one more thing?
 - Add a dummy entry to your Jenkins server's `/etc/hosts` file so that `testdocker` resolves to the same IP address as `docker.io`.
 - Try telling Jenkins to get the image `testdocker/9jkh/cicd-bare`

If _that_ still doesn't work then it tells us that it isn't caused by the code having "special case" handling for that URL (as there's no way it could recognize `testdocker/9jkh/cicd-bare` as being the same as `9jkh/cicd-bare`).
If it doesn't work then that suggests that it's actually a bug with the underlying docker libraries this plugin uses, rather than the plugin code itself.  I realize that that this isn't as good as a bugfix ;-) but finding where the bug is would get us a step closer to fixing it...

**Comment by lifeofguenter** [comment] 2018-06-27 10:18
sorry, I just downgraded my hub.docker.com account and switched over to gitlab.com for private images which works perfectly fine.

**Comment by pjdarton** [comment] 2018-07-17 22:03
Ok, if you're not in a position to investigate further then I'll close the issue.

If anyone else finds this issue and *is* in a position to investigate further then they can reopen it.

**Closed by pjdarton** 2018-07-17 22:03 UTC
