### ISSUE TITLE
Could not provision second build - Jenkins master hangs and need to be restarted

### ISSUE THREAD

**Issue by spbkelt** [jenkinsci/docker-plugin#543] opened 2017-10-24 23:16 UTC
I did setup Docker Cloud with template: pointed to DOCKER_HOST URI and image in Manage Jenkins/Configure System/Cloud

When i trigger test job, first one finishes with success, but second build for the same job without any additional actions and changes is not triggered at all hanging in 
"(pending—Waiting for next available executor) state" in build queue. 

docker-plugin: 1.0.2
jenkins: 2.73.2
docker engine: 
```
Client:
 Version:      17.09.0-ce
 API version:  1.31 (downgraded from 1.32)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.07.0-ce
 API version:  1.31 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   8784753
 Built:        Tue Aug 29 17:41:43 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

Stack trace: ( masked registry DNS name)
```
Oct 24, 2017 10:53:52 PM com.nirima.jenkins.plugins.docker.DockerCloud provision
 INFO: Asked to provision 1 slave(s) for: null
 Oct 24, 2017 10:53:52 PM com.nirima.jenkins.plugins.docker.DockerCloud provision
 INFO: Will provision 'registry2.****/aurea/eng.build/jenkins/jnlp-slave:3.10-1-alpine', for label: 'null', in cloud: 'DLB-1'
 Oct 24, 2017 10:53:52 PM com.nirima.jenkins.plugins.docker.DockerCloud addProvisionedSlave
 INFO: Provisioning 'registry2.*****/aurea/eng.build/jenkins/jnlp-slave:3.10-1-alpine' number '0' on 'DLB-1'; Total containers: '174'
 Oct 24, 2017 10:53:52 PM hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
 INFO: Started provisioning Image of registry2.****/aurea/eng.build/jenkins/jnlp-slave:3.10-1-alpine from DLB-1 with 1 executors. Remaining excess workload: 0
 Oct 24, 2017 10:53:52 PM com.nirima.jenkins.plugins.docker.DockerCloud provisionFromTemplate
 INFO: Trying to run container for registry2.****/aurea/eng.build/jenkins/jnlp-slave:3.10-1-alpine
 Oct 24, 2017 10:54:16 PM hudson.TcpSlaveAgentListener$ConnectionHandler run
 INFO: Accepted JNLP4-connect connection #2 from /172.18.0.130:38480
 Oct 24, 2017 10:54:20 PM com.nirima.jenkins.plugins.docker.DockerCloud removeJobTemplate
 WARNING: Couldn't remove template for job with id: 9
 Oct 24, 2017 10:54:24 PM hudson.model.Run execute
 INFO: TestJob #3 main build action completed: SUCCESS
 Oct 24, 2017 10:54:24 PM com.nirima.jenkins.plugins.docker.DockerSlave _terminate
 INFO: Disconnected computer
 Oct 24, 2017 10:54:24 PM jenkins.slaves.DefaultJnlpSlaveReceiver channelClosed
 WARNING: Computer.threadPoolForRemoting [#25] for DLB-1-ae2be65a0456 terminated
 java.nio.channels.ClosedChannelException
 	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer.onReadClosed(ChannelApplicationLayer.java:208)
 	at org.jenkinsci.remoting.protocol.ApplicationLayer.onRecvClosed(ApplicationLayer.java:222)
 	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:832)
 	at org.jenkinsci.remoting.protocol.FilterLayer.onRecvClosed(FilterLayer.java:287)
 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.onRecvClosed(SSLEngineFilterLayer.java:181)
 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.switchToNoSecure(SSLEngineFilterLayer.java:283)
 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processWrite(SSLEngineFilterLayer.java:503)
 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processQueuedWrites(SSLEngineFilterLayer.java:248)
 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doSend(SSLEngineFilterLayer.java:200)
 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doCloseSend(SSLEngineFilterLayer.java:213)
 	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.doCloseSend(ProtocolStack.java:800)
 	at org.jenkinsci.remoting.protocol.ApplicationLayer.doCloseWrite(ApplicationLayer.java:173)
 	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer$ByteBufferCommandTransport.closeWrite(ChannelApplicationLayer.java:311)
 	at hudson.remoting.Channel.close(Channel.java:1403)
 	at hudson.remoting.Channel.close(Channel.java:1356)
 	at hudson.slaves.SlaveComputer.closeChannel(SlaveComputer.java:708)
 	at hudson.slaves.SlaveComputer.access$800(SlaveComputer.java:96)
 	at hudson.slaves.SlaveComputer$3.run(SlaveComputer.java:626)
 	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 	at java.lang.Thread.run(Thread.java:745)
 
 Oct 24, 2017 10:54:40 PM com.nirima.jenkins.plugins.docker.DockerSlave$2 run
 INFO: Stopped container ae2be65a04566fd1a9375d8f05edba0a8644eaa764aeaad81fc46b41d7b74ac3
 Oct 24, 2017 10:54:40 PM com.nirima.jenkins.plugins.docker.DockerSlave$2 run
 INFO: Shutdowned slave for ae2be65a04566fd1a9375d8f05edba0a8644eaa764aeaad81fc46b41d7b74ac3
 Oct 24, 2017 10:54:41 PM com.nirima.jenkins.plugins.docker.DockerSlave$2 run
 INFO: Removed container ae2be65a04566fd1a9375d8f05edba0a8644eaa764aeaad81fc46b41d7b74ac3
```

**Comment by spbkelt** [comment] 2017-10-24 23:19
![image](https://user-images.githubusercontent.com/19993178/31972759-dbf42772-b92a-11e7-98fc-f7120f78e52b.png)

**Comment by u2g-tg** [comment] 2017-10-25 10:27
I think I am seeing this issue too, with docker-plugin and a jenkins/jnlp-slave Docker container. I am using a label to restrict where jobs can run - 'docker-agent' 

Only the first provision after Jenkins starts will work. The job (just a couple of basic shell commands) completes and the agent shuts down. Try to run the job again, and it will stay queued forever as "Jenkins doesn't have label docker-agent". If I stop and start jenkins-server (it is running in a container on the same host), then when it comes back, a docker agent will successfully provision and run the job. But the next one will fail. So it is a cached state within Jenkins. I suspect something is not being cleared up correctly when the docker agent shuts down. 

### Versions 
-      Jenkins : v. 2.73.2
-      docker : 17.09.0-ce
-      docker-plugin : 1.0.2
-      jenkins/jnlp-slave : latest
     
### Logs 

**hudson.slaves : FINEST**
`Oct 25, 2017 9:35:37 AM FINER hudson.slaves.NodeProvisioner
Consulting hudson.slaves.NodeProvisioner$StandardStrategyImpl@5e448df9 provisioning strategy with state StrategyState{label=docker-agent, snapshot=LoadStatisticsSnapshot{definedExecutors=0, onlineExecutors=0, connectingExecutors=0, busyExecutors=0, idleExecutors=0, availableExecutors=0, queueLength=1}, plannedCapacitySnapshot=0, additionalPlannedCapacity=1}
Oct 25, 2017 9:35:37 AM FINE hudson.slaves.NodeProvisioner
Excess workload 1 detected. (planned capacity=0,connecting capacity=0,Qlen=0,available=0&0,online=0,m=0.5)
Oct 25, 2017 9:35:38 AM INFO hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
Started provisioning Image of jenkins/jnlp-slave from pc1140sandbox with 1 executors. Remaining excess workload: 0
Oct 25, 2017 9:35:38 AM FINER hudson.slaves.NodeProvisioner
Provisioning strategy hudson.slaves.NodeProvisioner$StandardStrategyImpl@5e448df9 declared provisioning complete
Oct 25, 2017 9:35:42 AM FINE hudson.slaves.ChannelPinger
Set up a remote ping for JNLP4-connect connection from 172.17.0.1/172.17.0.1:40442
Oct 25, 2017 9:35:42 AM FINE hudson.slaves.ChannelPinger
setting up ping on JNLP4-connect connection from 172.17.0.1/172.17.0.1:40442 with a 300 seconds interval and 240 seconds timeout
Oct 25, 2017 9:35:42 AM FINE hudson.slaves.ChannelPinger
Ping thread started for hudson.remoting.Channel@112ada15:JNLP4-connect connection from 172.17.0.1/172.17.0.1:40442 with a 300 seconds interval and a 240 seconds timeout
Oct 25, 2017 9:35:43 AM FINE hudson.slaves.WorkspaceList
acquired /home/jenkins/workspace/test-docker-agent2
java.lang.Throwable: from hudson.slaves.WorkspaceList@7fe4882a
	at hudson.slaves.WorkspaceList.acquire(WorkspaceList.java:263)
	at hudson.slaves.WorkspaceList.allocate(WorkspaceList.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.decideWorkspace(AbstractBuild.java:443)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:480)
	at hudson.model.Run.execute(Run.java:1737)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:421)

Oct 25, 2017 9:35:54 AM FINE hudson.slaves.WorkspaceList
releasing /home/jenkins/workspace/test-docker-agent2 with lock count 1
java.lang.Throwable: from hudson.slaves.WorkspaceList@7fe4882a
	at hudson.slaves.WorkspaceList._release(WorkspaceList.java:210)
	at hudson.slaves.WorkspaceList.access$300(WorkspaceList.java:48)
	at hudson.slaves.WorkspaceList$1.release(WorkspaceList.java:278)
	at hudson.model.AbstractBuild$AbstractBuildExecution.cleanUp(AbstractBuild.java:640)
	at hudson.model.Build$BuildExecution.cleanUp(Build.java:201)
	at hudson.model.Run.execute(Run.java:1784)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:421)

Oct 25, 2017 9:35:54 AM FINE hudson.slaves.ChannelPinger
Terminating ping thread for JNLP4-connect connection from 172.17.0.1/172.17.0.1:40442
Oct 25, 2017 9:36:40 AM FINER hudson.slaves.NodeProvisioner
Consulting hudson.slaves.NodeProvisioner$StandardStrategyImpl@5e448df9 provisioning strategy with state StrategyState{label=docker-agent, snapshot=LoadStatisticsSnapshot{definedExecutors=0, onlineExecutors=0, connectingExecutors=0, busyExecutors=0, idleExecutors=0, availableExecutors=0, queueLength=1}, plannedCapacitySnapshot=1, additionalPlannedCapacity=0}
Oct 25, 2017 9:36:40 AM FINER hudson.slaves.NodeProvisioner
Consulting io.jenkins.docker.FastNodeProvisionerStrategy@2e17fde8 provisioning strategy with state StrategyState{label=docker-agent, snapshot=LoadStatisticsSnapshot{definedExecutors=0, onlineExecutors=0, connectingExecutors=0, busyExecutors=0, idleExecutors=0, availableExecutors=0, queueLength=1}, plannedCapacitySnapshot=1, additionalPlannedCapacity=0}
Oct 25, 2017 9:36:40 AM FINER hudson.slaves.NodeProvisioner
Provisioning strategy io.jenkins.docker.FastNodeProvisionerStrategy@2e17fde8 declared provisioning complete
Oct 25, 2017 9:37:17 AM FINER hudson.slaves.NodeProvisioner
Queue length 0 is less than the available capacity 0. No provisioning strategy required
Oct 25, 2017 9:37:17 AM FINER hudson.slaves.NodeProvisioner
Consulting hudson.slaves.NodeProvisioner$StandardStrategyImpl@5e448df9 provisioning strategy with state StrategyState{label=docker-agent, snapshot=LoadStatisticsSnapshot{definedExecutors=0, onlineExecutors=0, connectingExecutors=0, busyExecutors=0, idleExecutors=0, availableExecutors=0, queueLength=1}, plannedCapacitySnapshot=1, additionalPlannedCapacity=0}
Oct 25, 2017 9:37:17 AM FINER hudson.slaves.NodeProvisioner
Consulting io.jenkins.docker.FastNodeProvisionerStrategy@2e17fde8 provisioning strategy with state StrategyState{label=docker-agent, snapshot=LoadStatisticsSnapshot{definedExecutors=0, onlineExecutors=0, connectingExecutors=0, busyExecutors=0, idleExecutors=0, availableExecutors=0, queueLength=1}, plannedCapacitySnapshot=1, additionalPlannedCapacity=0}
Oct 25, 2017 9:37:17 AM FINER hudson.slaves.NodeProvisioner
Provisioning strategy io.jenkins.docker.FastNodeProvisionerStrategy@2e17fde8 declared provisioning complete
Oct 25, 2017 9:37:17 AM FINER hudson.slaves.NodeProvisioner
Queue length 0 is less than the available capacity 2. No provisioning strategy required
...`

**com.nirima.jenkins : FINEST
io.jenkins.docker : FINEST** 
`...
Oct 25, 2017 10:23:07 AM FINE io.jenkins.docker.FastNodeProvisionerStrategy
Provisioning completed
Oct 25, 2017 10:23:17 AM FINE io.jenkins.docker.FastNodeProvisionerStrategy
Available capacity=1, currentDemand=1
Oct 25, 2017 10:23:17 AM FINE io.jenkins.docker.FastNodeProvisionerStrategy
Provisioning completed
Oct 25, 2017 10:23:27 AM FINE io.jenkins.docker.FastNodeProvisionerStrategy
Available capacity=1, currentDemand=1
Oct 25, 2017 10:23:27 AM FINE io.jenkins.docker.FastNodeProvisionerStrategy
Provisioning completed
Oct 25, 2017 10:23:37 AM FINE io.jenkins.docker.FastNodeProvisionerStrategy
Available capacity=1, currentDemand=1
Oct 25, 2017 10:23:37 AM FINE io.jenkins.docker.FastNodeProvisionerStrategy
Provisioning completed
Oct 25, 2017 10:23:47 AM FINE io.jenkins.docker.FastNodeProvisionerStrategy
Available capacity=1, currentDemand=1
Oct 25, 2017 10:23:47 AM FINE io.jenkins.docker.FastNodeProvisionerStrategy
Provisioning completed
Oct 25, 2017 10:23:57 AM FINE io.jenkins.docker.FastNodeProvisionerStrategy
Available capacity=1, currentDemand=1
Oct 25, 2017 10:23:57 AM FINE io.jenkins.docker.FastNodeProvisionerStrategy
Provisioning completed
...`

My reading of the logs is that the problem is `plannedCapacitySnapshot=1` which comes from the NodeProvisioner state. So the docker-plugin thinks it doesn't need to create a new slave/agent. But there are no slaves/agents running at that point so it must be stale data? Querying hudson.instance.slaves there is nothing, neither on the Jenkins Web GUI manage Nodes page. 

I'm at my limits with debugging this.

**Comment by ndeloof** [comment] 2017-10-25 18:52
You're right that `plannedCapacitySnapshot` is wrong here, need to investigate how to force this being updated. 
I guess you have configured template with default max capacity of 1.
This parameter is stupid, provisioning docker container should be limited by available resources, not number of containers.

**Comment by ndeloof** [comment] 2017-10-25 22:29
I was able to reproduce once in a debug session by chance. A PlannedNode was referenced by NodeProvisioner but had no attached container, so keep counting as endless pending and counting for one slot. As a result no new node is allocated.
I can't reproduce anymore, and don't know how I went into this state :'(

**Comment by ndeloof** [comment] 2017-10-25 22:34
Interestingly I can reproduce as described if I configure plugin to run on jenkins 2.73.2

**Comment by ensean** [comment] 2017-10-26 01:50
My software stack version is the same as @u2g-tg  and I am facing the same issue. Once I restart the Jenkins master, build4 gets started properly.  BTW, it cost me about 2 days to get **docker plugin** & **jenkins/jnlp-slave** image worked. I strongly suggest a wiki page for the usage of this plugin ...

![image](https://user-images.githubusercontent.com/12255172/32031177-3a182ef8-b9c5-11e7-8d5e-6d4f4f852e25.png)

**Comment by ndeloof** [comment] 2017-10-26 07:07
@ensean 
> BTW, it cost me about 2 days to get docker plugin & jenkins/jnlp-slave image worked. I strongly suggest a wiki page for the usage of this plugin ...

you're welcome to create a new page for it on jenkins wiki, or a dedicated section on http://wiki.jenkins-ci.org/display/JENKINS/Docker+Plugin. I'd like to know what prevented you to get this running out of the box, and what has been required to fix it, so we can at least provide a better help tips on web UI.

**Comment by ensean** [comment] 2017-10-26 08:19
@ndeloof 
> I'd like to know what prevented you to get this running out of the box, and what has been required to fix it, so we can at least provide a better help tips on web UI.

As as new user, I encountered the following troubles while trying to get this plugin work together with [jenkinsci/jnlp-slave](https://hub.docker.com/r/jenkinsci/jnlp-slave/)    

- The entry path of this plugin's UI, I found it by ```luck```, to be honest
-  The setting of ``` secret ``` and ``` agent_name``` parameter of the jnlp-slave image, I tried to set them though docker ENV parameter, but it seems to be useless, .  A guide of docker image req and config would be great.

**Comment by ndeloof** [comment] 2017-10-26 08:29
> The entry path of this plugin's UI, I found it by luck, to be honest

ok, so this is a newcomer issue here. wiki could indeed be improved on this topic

> The setting of secret and agent_name parameter of the jnlp-slave image, I tried to set them though docker ENV parameter, but it seems to be useless, . A guide of docker image req and config would be great.

so you actually have been thinking too much before giving it a try :D

**Comment by ensean** [comment] 2017-10-26 09:04
This may be considered as mislead caused by the jnlp-slave image @_@
> so you actually have been thinking too much before giving it a try :D

I tried several times and only find a ```ClosedChannelException``` in the log, may this be helpful for investigation ?

```
Oct 26, 2017 4:44:34 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud provision
Asked to provision 1 slave(s) for: agent-jnlp
Oct 26, 2017 4:44:34 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud provision
Will provision 'jenkinsci/jnlp-slave', for label: 'agent-jnlp', in cloud: 'agent-pool'
Oct 26, 2017 4:44:35 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud addProvisionedSlave
Provisioning 'jenkinsci/jnlp-slave' number '0' on 'agent-pool'; Total containers: '1'
Oct 26, 2017 4:44:35 PM INFO org.jenkinsci.plugins.cloudstats.CloudStatistics logTypeNotSupported
No support for cloud-stats plugin by class hudson.slaves.NodeProvisioner$PlannedNode
Oct 26, 2017 4:44:35 PM INFO hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
Started provisioning Image of jenkinsci/jnlp-slave from agent-pool with 1 executors. Remaining excess workload: 0
Oct 26, 2017 4:44:35 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud provisionFromTemplate
Trying to run container for jenkinsci/jnlp-slave
Oct 26, 2017 4:44:36 PM INFO org.jenkinsci.plugins.cloudstats.CloudStatistics logTypeNotSupported
No support for cloud-stats plugin by class com.nirima.jenkins.plugins.docker.DockerComputer
Oct 26, 2017 4:44:37 PM INFO hudson.TcpSlaveAgentListener$ConnectionHandler run
Accepted JNLP4-connect connection #1 from 172.17.0.1/172.17.0.1:40094
Oct 26, 2017 4:44:43 PM INFO hudson.model.Run execute
docker-agent-jnlp-1 #5 main build action completed: SUCCESS
Oct 26, 2017 4:44:43 PM INFO com.nirima.jenkins.plugins.docker.DockerSlave _terminate
Disconnected computer
Oct 26, 2017 4:44:43 PM WARNING jenkins.slaves.DefaultJnlpSlaveReceiver channelClosed
Computer.threadPoolForRemoting [#10] for agent-pool-da7a67996453 terminated
java.nio.channels.ClosedChannelException
	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer.onReadClosed(ChannelApplicationLayer.java:208)
	at org.jenkinsci.remoting.protocol.ApplicationLayer.onRecvClosed(ApplicationLayer.java:222)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:832)
	at org.jenkinsci.remoting.protocol.FilterLayer.onRecvClosed(FilterLayer.java:287)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.onRecvClosed(SSLEngineFilterLayer.java:181)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.switchToNoSecure(SSLEngineFilterLayer.java:283)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processWrite(SSLEngineFilterLayer.java:503)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processQueuedWrites(SSLEngineFilterLayer.java:248)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doSend(SSLEngineFilterLayer.java:200)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doCloseSend(SSLEngineFilterLayer.java:213)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.doCloseSend(ProtocolStack.java:800)
	at org.jenkinsci.remoting.protocol.ApplicationLayer.doCloseWrite(ApplicationLayer.java:173)
	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer$ByteBufferCommandTransport.closeWrite(ChannelApplicationLayer.java:311)
	at hudson.remoting.Channel.close(Channel.java:1403)
	at hudson.remoting.Channel.close(Channel.java:1356)
	at hudson.slaves.SlaveComputer.closeChannel(SlaveComputer.java:708)
	at hudson.slaves.SlaveComputer.access$800(SlaveComputer.java:96)
	at hudson.slaves.SlaveComputer$3.run(SlaveComputer.java:626)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Oct 26, 2017 4:44:54 PM INFO com.nirima.jenkins.plugins.docker.DockerSlave$2 run
Stopped container da7a67996453aa94a1de600697ef8296b524825f3b88a6a72cc896779f822bfd
Oct 26, 2017 4:44:54 PM INFO com.nirima.jenkins.plugins.docker.DockerSlave$2 run
Shutdowned slave for da7a67996453aa94a1de600697ef8296b524825f3b88a6a72cc896779f822bfd
Oct 26, 2017 4:44:54 PM INFO com.nirima.jenkins.plugins.docker.DockerSlave$2 run
Removed container da7a67996453aa94a1de600697ef8296b524825f3b88a6a72cc896779f822bfd
```

**Comment by ndeloof** [comment] 2017-10-26 09:05
@spbkelt IIUC you're using job properties to define template for your job. Can you please try using a "classic" agent template in system configuration > cloud to double check this has any impact ?

**Comment by ndeloof** [comment] 2017-10-26 09:08
@ensean can you please open a separate issue for this discussion ?

**Comment by ndeloof** [comment] 2017-10-26 09:16
Are you by chance using agent template defined as a Job Property ? I can see in @spbkelt 's log this line:
`com.nirima.jenkins.plugins.docker.DockerCloud removeJobTemplate`

could you please share this property configuration so I double check ?

**Comment by u2g-tg** [comment] 2017-10-26 09:48
@ndeloof I am not using a template from a Job, just referencing a label from the job (in the 'where can it build restriction') , where the label is defined on the template in the Jenkins settings > Cloud > Docker section.

**Comment by u2g-tg** [comment] 2017-10-26 09:59
Logs from a successful run (first after Jenkins restart) 
[jenkins_log_1run.txt](https://github.com/jenkinsci/docker-plugin/files/1417835/jenkins_log_1run.txt)
[docker-plugin_log.txt](https://github.com/jenkinsci/docker-plugin/files/1417836/docker-plugin_log.txt)
[hudson_slaves_log.txt](https://github.com/jenkinsci/docker-plugin/files/1417837/hudson_slaves_log.txt)

**Comment by u2g-tg** [comment] 2017-10-26 10:08
Logs after the 2nd (hanging) job is requested. 
[docker-plugin_log2.txt](https://github.com/jenkinsci/docker-plugin/files/1417858/docker-plugin_log2.txt)
[hudson_slaves_log2.txt](https://github.com/jenkinsci/docker-plugin/files/1417859/hudson_slaves_log2.txt)
There is no change in the Jenkins logs :/ 

Interestingly, I tried running another job that just does a shell 'echo hello world' and is not restricted on where to run, so should be able to run on one of the two master executors, but that is also blocked in the queue. 

The state of that job is `(pending—Jenkins is reserved for jobs with matching label expression)`

Any ideas?

**Comment by ndeloof** [comment] 2017-10-26 11:41
@u2g-tg can you please run :
```
def label = hudson.model.Label.get("docker-ssh")
println label.nodes
println label.nodeProvisioner.pendingLaunches
```
This would (at least) confirm issue is that node provisioner still reference a pending launch while no docker slave is actually pending.

**Comment by alexeygrigorovaurea** [comment] 2017-10-26 20:53
Hi @ndeloof 
here is report for same issue on fresh jenkins
[support_2017-10-26_20.35.53.zip](https://github.com/jenkinsci/docker-plugin/files/1420000/support_2017-10-26_20.35.53.zip)
job config
jenkins@4a65f9950436:~/jobs/test jnlp$ cat config.xml 
<?xml version='1.0' encoding='UTF-8'?>
<project>
  <description></description>
  <keepDependencies>false</keepDependencies>
  <properties/>
  <scm class="hudson.scm.NullSCM"/>
  <assignedNode>jnlp</assignedNode>
  <canRoam>false</canRoam>
  <disabled>false</disabled>
  <blockBuildWhenDownstreamBuilding>false</blockBuildWhenDownstreamBuilding>
  <blockBuildWhenUpstreamBuilding>false</blockBuildWhenUpstreamBuilding>
  <triggers/>
  <concurrentBuild>false</concurrentBuild>
  <builders>
    <hudson.tasks.Shell>
      <command>echo hi</command>
    </hudson.tasks.Shell>
  </builders>
  <publishers/>
  <buildWrappers/>
</project>jenkins@4a65f9950436:~/jobs/test jnlp$ 

script result
![image](https://user-images.githubusercontent.com/28352910/32076346-4b6aa792-baa8-11e7-8691-b9cc7433c5d7.png)

log
Accepted JNLP4-connect connection #2 from 172.17.0.1/172.17.0.1:57138
Oct 26, 2017 8:31:46 PM INFO hudson.model.Run execute
test jnlp #1 main build action completed: SUCCESS
Oct 26, 2017 8:31:47 PM INFO com.nirima.jenkins.plugins.docker.DockerSlave _terminate
Disconnected computer

**Comment by ndeloof** [comment] 2017-10-26 22:23
I think I've found the root cause for this and was able to reproduce.
Fixed by https://github.com/jenkinsci/docker-plugin/commit/910e53af70af779ea0e68846432ac7f2c8b12d09

You can give it a try by using latest CI build from https://ci.jenkins.io/job/Plugins/job/docker-plugin/job/master/54/

**Comment by alexeygrigorovaurea** [comment] 2017-10-26 23:11
it works ok
there was a message in the log as below, after applying that  property plugin works fine

> Rejecting connection to mycloud-b2ab0232a7f0 from 172.17.0.1/172.17.0.1:58464 as a JNLP agent as the launcher class io.jenkins.docker.connector.DockerComputerJNLPConnector$1 does not extend JNLPLauncher or does not implement DelegatingComputerLauncher with a delegation chain leading to a JNLPLauncher. Set system property jenkins.slaves.DefaultJnlpSlaveReceiver.disableStrictVerification=true to allowconnections until the plugin has been fixed.

**Comment by ndeloof** [comment] 2017-10-27 07:21
oh right, I forgot about this constraint on JNLP launcher ...

**Comment by spbkelt** [comment] 2017-10-27 18:11
So what is the current status of fix? Can we expect new release?

**Comment by ndeloof** [comment] 2017-10-27 19:32
I just released 1.0.4

**Closed by ndeloof** 2017-10-27 19:32 UTC
Labels: bug

**Comment by spbkelt** [comment] 2017-10-30 09:07
I see latest **1.0.3** https://plugins.jenkins.io/docker-plugin

**Comment by ndeloof** [comment] 2017-10-30 09:59
http://updates.jenkins-ci.org/download/plugins/docker-plugin/

**Comment by u2g-tg** [comment] 2017-10-30 11:01
@ndeloof  Great work, repeatable jnlp jobs with the docker-plugin now (v1.0.4), many thanks!

**Comment by alexeygrigorovaurea** [comment] 2017-10-30 14:21
++ Thanks Nicolas
