### ISSUE TITLE
ssh Connection Timeout, max no of retries and seconds to wait between retries has no effect

### ISSUE THREAD

**Issue by pitargue** [jenkinsci/docker-plugin#605] opened 2018-01-11 22:26 UTC
docker-plugin version 1.1.2
Jenkins version 2.101
Docker version 1.12.6, build ec8512b/1.12.6

Using ssh connection method to jenkins agents in local docker cloud, configuring:
  Connection Timeout in Seconds
  Maximum Number of Retries
  Seconds To Wait Between Retries

seems to have no effect.  The logs always say trying for 30 times as fast as it can.  (Our slaves come up real slow so need a bit of delay.)

SEVERE: Failed to connect to docker-sys4:32841 (try 1/30) - There was a problem while connecting to docker-sys4:32841

...

SEVERE: Failed to connect to docker-sys4:32842 (try 30/30) - There was a problem while connecting to docker-sys4:32842
Jan 11, 2018 1:59:02 PM com.nirima.jenkins.plugins.docker.DockerCloud$1 run
SEVERE: Error in provisioning; template='DockerTemplate{configVersion=2, labelString='bvs', connector=io.jenkins.docker.connector.DockerComputerSSHConnector@453e723d, remoteFs='/root', instanceCap=10, mode=EXCLUSIVE, retentionStrategy=com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy@769c3fe9, dockerTemplateBase=DockerTemplateBase{image='localhost:5000/bvsimages/centos7-systemd-with-bvs:latest', pullCredentialsId='', registry=null, dockerCommand='/usr/lib/systemd/systemd --switched-root --system', hostname='', dnsHosts=[], network='', volumes=[/mnt/tank/bvs:/mnt/tank/bvs], volumesFrom2=[], environment=[TZ=America/Los_Angeles], bindPorts='', bindAllPorts=false, memoryLimit=null, memorySwap=null, cpuShares=null, privileged=true, tty=true, macAddress='null', extraHosts=[]}, removeVolumes=true, pullStrategy=PULL_NEVER, nodeProperties=[]}' for cloud='docker'
java.io.IOException: SSH service didn't started after 60s.

Any other info I can provide?

**Comment by rahulakash** [comment] 2018-05-02 16:39
We are observing similar issue with the following versions: 

> Docker-plugin: 1.1.4
> Jenkins: 2.107.1
> Docker: 17.06.0-ce, build 02c1d87

Downgrading seems to be the only way out at this point. Any help on this is highly appreciated.

**Comment by daxgames** [comment] 2018-05-30 11:26
@rahulakash Downgrading what?

**Comment by rahulakash** [comment] 2018-06-03 17:37
@daxgames The docker-plugin.

**Comment by daxgames** [comment] 2018-06-04 23:26
@rahulakash to what version.

**Comment by rahulakash** [comment] 2018-06-04 23:52
@daxgames 0.16.2.

**Comment by pjdarton** [comment] 2018-06-05 09:12
@rahulakash Can you confirm that both 1.0.4 and 0.17.0 do _not_ work for you and that 0.16.2 is the latest that works for you?

Knowing the exact versions that do/don't work for you may assist in tracking down the changes that were responsible for breaking it in your situation (and thus help folks work out how to fix it for later versions).

**Comment by rahulakash** [comment] 2018-06-10 19:33
@pjdarton I can confirm that we were unable to get the slaves running with 1.0.4. So, we had to downgrade to a version which was working for us before, which is 0.16.2. But, I am really not sure if this works with 0.17.0 though.

I will test this with 0.17.0 and share the results here later. Thanks.

**Comment by ccureau** [comment] 2018-08-15 23:47
I briefly looked over the code for the SSH connector back to tagged version 0.1, but I saw no evidence of this ever working.  I did see that somewhere around 1.0.4 it changed from 60 retries at 2 second intervals to 30 retries at 2 second intervals because of a refactoring of code.  

However, It works now.  :)

This is important to us because some containers take an extremely long time to spin up and provision.

 #677

**Comment by pjdarton** [comment] 2018-08-16 15:07
OK, I can see #677 is a fairly simple code change, so if we can get that into an acceptable state (i.e. fix the unit tests that it broke) then I can't see any reason not to merge that in so it'll be in the next release.

Until that's all done and merged in, I'd recommend folks using containers that take "an extremely long time to spin up and provision" investigate using JNLP or the "direct" connection method - the plugin's support for JNLP is now sufficiently flexible that you can do JNLP with pretty much any container if you configure the plugin correctly, and that could be less fussy about spin-up times than SSH is.

**Comment by pjdarton** [comment] 2018-08-16 17:18
Personally, I've found SSH no more immune to disconnects than JNLP.
SSH is unix-only and unix isn't as liable to randomly disconnect as Windows VMs are - when Microsoft Windows encounters a transient network outage, e.g. the network link dropping briefly, Windows kills all established TCP connections (preventing the TCP protocol "just dealing with it" and thus ensuring that it's unable to shield the applications from the issue), and it's that which kills JNLP and SSH connections alike.
i.e. IME JNLP is only guilty by association with Windows - it's Windows that's guilty as hell.

If you don't like JNLP then try the direct-attach method - that only requires a connection to the docker host and hence may even be more efficient than either SSH or JNLP.

i.e. Try everything :-)

**Comment by pjdarton** [comment] 2020-08-13 11:43
I believe this was fixed by #718 which went into release 1.1.8

**Closed by pjdarton** 2020-08-13 11:43 UTC
