### ISSUE TITLE
using this plugin with docker 1.12 doesn't work even after 0.16.2 upgrade

### ISSUE THREAD

**Issue by adityacs** [jenkinsci/docker-plugin#441] opened 2016-09-22 14:55 UTC
I can see the container spinning up in the docker machine but Jenkins doesn't start the build. Could anyone let me know how to resolve this issue?

Thanks

**Comment by pashok2398** [comment] 2016-10-10 10:41
+1
Downgrade to 1.10, this is what i did, in 1.12 API is changed.
Need to be fixed.

**Comment by LINKIWI** [comment] 2016-10-12 15:01
Same here--a symptom is that builds are indefinitely stuck on `pending—Waiting for next available executor`. Downgrading `docker-engine` to 1.11.2 via `apt-get` seemed to fix the issue for me.

**Comment by adityacs** [comment] 2016-10-16 09:56
Wanted to use dockers inbuilt service discovery and orchestration which is available only in 1.12 version. No options but to wait till we get updated plugin.

**Comment by Loki-Afro** [comment] 2016-10-22 08:23
You can specify the docker api version in the main cloud configuration, that will solve your problems

**Comment by cchene** [comment] 2016-11-18 08:09
Is this a duplicate of #403?

**Comment by adityacs** [comment] 2016-11-19 08:33
@Loki-Afro , Even after mentioning API version it didn't work for me. 

@cchene , Yeah might be same as #403. Not very sure

**Comment by ndeloof** [comment] 2017-09-11 12:28
assumed to be same as #403 without more details

**Closed by ndeloof** 2017-09-11 12:28 UTC
