### ISSUE TITLE
When images fail to launch, offline nodes are not deleted

### ISSUE THREAD

**Issue by bartmeuris** [jenkinsci/docker-plugin#106] opened 2014-10-16 12:57 UTC
When an image fails to launch (which I encountered due to #105 ) - the resulting "nodes" in Jenkins are offline and not deleted.

**Comment by cristianokbc** [comment] 2015-03-27 13:57
+1

**Comment by samrocketman** [comment] 2015-10-31 00:51
I've discovered this bug as well.

**Comment by samrocketman** [comment] 2015-10-31 00:55
This happens for me as well.  To clean up all offline slaves and delete them in Jenkins use the following Script Console script.

```groovy
println "Cleaning up offline slaves..."
hudson.model.Hudson.instance.slaves.each {
  if(it.getComputer().isOffline()) {
    println "Deleting ${it.name}"
    it.getComputer().doDoDelete()
  }
}
println "Done."
```

**Comment by KostyaSha** [comment] 2015-11-01 03:51
@samrocketman Have you waited at least for 10 minutes?  There is a delay that deletes slaves automatically, but this should happen only in abnormal situation. You should investigate why there are not deleted automatically as it may be some design/jenkins issue.

**Comment by KostyaSha** [comment] 2015-11-01 03:51
Closing because it was improved long some releases ago.

**Closed by KostyaSha** 2015-11-01 03:51 UTC

**Comment by samrocketman** [comment] 2015-11-01 05:09
This should remain open as I was able to reproduce this issue (by having an SSH container start but Jenkins not having credentials to connect).  The ideal scenario here is:

* If Jenkins tries launching an image it AND after launching it fails to launch the agent software.  It shouldn't continue to try to spin up additional images of the same type.  It should probably throw some additional errors stating something needs to be updated but not keep trying to launch more failed images.

In my case, the experience was infinite resource growth of spinning up docker containers had I not caught the issue immediately because I was testing.

**Comment by KostyaSha** [comment] 2015-11-01 10:47
If you have correct total number of slaves they will stop provisioning by hitting total limit and will be deleted after 10 minutes idle after fixing configuration. Currently code doesn't differ error cases because even credential issue can be caused by docker host server side configuration.

**Comment by thomassuckow** [comment] 2015-11-04 21:24
I wonder how reasonable it would be to implement an exponential backoff for failed launches of a node.

**Comment by dshamanthreddy** [comment] 2017-10-03 17:48
samrocketman Thanks for script 
println "Cleaning up offline slaves..."
hudson.model.Hudson.instance.slaves.each {
  if(it.getComputer().isOffline()) {
    println "Deleting ${it.name}"
    it.getComputer().doDoDelete()
  }
}
println "Done."


But When run this as jenkins job it fail , It work in Jenkins script console only . how do we fix this ??

**Comment by samrocketman** [comment] 2017-10-03 23:44
@dshamanthreddy I'd rather not hijack this thread with conversation unrelated to it.  Web search"how to run groovy scripts jenkins".
