### ISSUE TITLE
SSH service hadn't started after 0 seconds

### ISSUE THREAD

**Issue by eliasbalasis** [jenkinsci/docker-plugin#760] opened 2019-11-11 12:13 UTC
We use SSH connect method and build job images containing an SSH server which run successfully with other Cloud Providers for Docker.
Strangely this didn't work with jenkins/ssh-slave image either.

Docker Plugin Version = 1.1.8
Jenkins Versioun = 2.190.2
Docker Engine Version = 17.09.0-ce

All attempts are producing the following error:

`
java.io.IOException: SSH service hadn't started after 0 seconds.
        at io.jenkins.docker.connector.DockerComputerSSHConnector.createLauncher(DockerComputerSSHConnector.java:261)
        at io.jenkins.docker.connector.DockerComputerConnector.createLauncher(DockerComputerConnector.java:91)
        at com.nirima.jenkins.plugins.docker.DockerTemplate.doProvisionNode(DockerTemplate.java:564)
        at com.nirima.jenkins.plugins.docker.DockerTemplate.provisionNode(DockerTemplate.java:526)
        at com.nirima.jenkins.plugins.docker.DockerCloud$1.run(DockerCloud.java:364)
        at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
        at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
`

**Comment by grostarin** [comment] 2019-11-12 09:25
Same problem here.
Workaround : I downgrade to 1.1.7

**Comment by pjdarton** [comment] 2019-11-12 10:31
This is a duplicate of bug report #751 which was fixed in #752 which will be FITNR _and_ also includes links to a pre-release build of the bugfixed code.

**Closed by pjdarton** 2019-11-12 10:31 UTC

**Comment by eliasbalasis** [comment] 2019-11-12 11:19
Many thanks,
when are you planning to release the fix in #752 ?

**Comment by pjdarton** [comment] 2019-11-22 18:38
Code changes went into released of docker-plugin version 1.1.9
