### ISSUE TITLE
Volumes bind mount is not multi-line anymore..

### ISSUE THREAD

**Issue by Tibo75** [jenkinsci/docker-plugin#571] opened 2017-12-11 09:05 UTC
docker-plugin : 1.1
jenkins : 2.73.3
docker : 17.03.1-ce

Hi,

All mounts are now concatenated in one unique line and I can't find a way to set it back to multiline, even patching the config.xml itself..

![image](https://user-images.githubusercontent.com/7880950/33823194-7c872384-de5a-11e7-8466-806dab4f57af.png)

This prevents from running any new container : 
```
Error in provisioning; template='DockerTemplate{configVersion=2, labelString='dockerslave', connector=io.jenkins.docker.connector.DockerComputerSSHConnector@4d4c50f0, remoteFs='/home/jenkins', instanceCap=2, mode=EXCLUSIVE, retentionStrategy=com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy@4ffb5590, numExecutors=1, dockerTemplateBase=DockerTemplateBase{image='nexus.assurances.group.gca:8093/caagis/jenkins-docker-slave', pullCredentialsId='', registry=DockerRegistryEndpoint[null;credentialsId=null], dockerCommand='', hostname='', dnsHosts=[], network='dockercntlm_proxy', volumes=[/var/run/docker.sock:/var/run/docker.sock/usr/lib64/libltdl.so.7:/usr/lib/x86_64-linux-gnu/libltdl.so.7/usr/bin/docker:/usr/bin/docker/data/local_caches/maven/repo:/home/jenkins/.m2/repository/data/local_caches/npm/:/data/npm//data/local_caches/yarn:/home/jenkins/.cache/yarn], volumesFrom2=[], environment=[], bindPorts='', bindAllPorts=false, memoryLimit=null, memorySwap=null, cpuShares=null, privileged=false, tty=false, macAddress='null', extraHosts=[nexus.caagis-intra.credit-agricole.fr:10.108.96.67, pic.assurances.group.gca:10.108.99.8, nexus.assurances.group.gca:10.108.99.8, gitlab.assurances.group.gca:10.215.70.177]}, removeVolumes=false, pullStrategy=PULL_LATEST, nodeProperties=[]}' for cloud='Docker Container'
java.lang.IllegalArgumentException
	at com.github.dockerjava.api.model.Bind.parse(Bind.java:130)
Caused: java.lang.IllegalArgumentException: Error parsing Bind '/var/run/docker.sock:/var/run/docker.sock/usr/lib64/libltdl.so.7:/usr/lib/x86_64-linux-gnu/libltdl.so.7/usr/bin/docker:/usr/bin/docker/data/local_caches/maven/repo:/home/jenkins/.m2/repository/data/local_caches/npm/:/data/npm//data/local_caches/yarn:/home/jenkins/.cache/yarn'
```

And in case it would be related, I'm also observing  this on 2 differents line sin the "Manage Old Data"  screen: 
```
MissingFieldException: No field 'remoteFsMapping' found in class 'com.nirima.jenkins.plugins.docker.action.DockerBuildAction'


MissingFieldException: No field 'idleMinutes' found in class 'com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy', MissingFieldException: No field 'remoteFsMapping' found in class 'com.nirima.jenkins.plugins.docker.DockerTemplate', MissingFieldException: No field 'idleMinutes' found in class 'com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy', MissingFieldException: No field 'lxcConfString' found in class 'com.nirima.jenkins.plugins.docker.DockerTemplateBase'

```

Any idea to quickly patch this is more than welcome !

**Comment by ncreuschling** [comment] 2017-12-11 09:22
This needs to be dealt with urgently. This bug affects the input fields of "Volumes", "Volumes From" and perhaps some more.

**Comment by ncreuschling** [comment] 2017-12-11 09:34
We just downgraded to v1.0.4 of this plugin and voila: the fields are multi-line again.

**Comment by ncreuschling** [comment] 2017-12-11 09:43
![brokenmultiline](https://user-images.githubusercontent.com/637855/33824843-f615924e-de5f-11e7-96cc-2a1637679145.png)

This is what it looks like with v1.1.

We can't go back to v1.0.4 because now Jenkins reports our templates as broken… Guess we are stuck at the moment.

**Comment by ndeloof** [comment] 2017-12-11 09:51
this has been fixed already by https://github.com/jenkinsci/docker-plugin/pull/566
1.1.1 will be released soon (investigating https://github.com/jenkinsci/docker-plugin/issues/568 for now, but could release it without this fixed then 1.1.2 later for it)

**Closed by ndeloof** 2017-12-11 09:51 UTC

**Comment by ncreuschling** [comment] 2017-12-11 09:53
OK - we just downgraded successfully. We seem to have lost the setting "Docker Host URI" which resulted in messages about broken templates.

Thank you @ndeloof.

**Comment by Tibo75** [comment] 2017-12-11 10:25
I do confirm downgrading recovers the multi-line functionality losing the "Docker Host URI" value.

I think I'm now facing issue #568, but will follow up there.

Thanks for the update @ndeloof and sorry for the unnecessary issue.

**Comment by ndeloof** [comment] 2017-12-11 12:43
no worries, better to report issue to alert me about regression

**Comment by ndeloof** [comment] 2017-12-11 12:46
@Tibo75 please see my last comment on #568, I miss feedback to reproduce/diagnose/fix it
