### ISSUE TITLE
Retries in ConnectionCheckSSH

### ISSUE THREAD

**Issue by php50350** [jenkinsci/docker-plugin#751] opened 2019-10-01 03:51 UTC
In the execute method of ConnectionCheckSSH, there is a line of code as follow:

`final int retries = Math.min(0, parent.retries);`

That causes the number of retries to be always 0 (unless the parent.retries is negative). The result is that when the plugin starts a Docker container and then attempts to connect to it, the error "java.io.IOException: SSH service hadn't started after 0 seconds." will often be encountered.

**Comment by pjdarton** [comment] 2019-10-01 09:10
"oops"
Yes, that looks like a bit of an oversight on my part.
...and that code has no unit-tests so this one slipped through.

I'll fix it.

**Comment by pjdarton** [comment] 2019-10-01 10:43
OK, I've created PR #752 that should fix this.  It's building on ci.jenkins.io at present (right now it's successfully run the build and tests and is waiting for an executor to save the final results).

Once it's built, you should be able to get a `.hpi` file from the "Last Successful Artifacts" listed under https://ci.jenkins.io/job/Plugins/job/docker-plugin/job/PR-752/
Once that's available, please download it, install it on your Jenkins server(s) [manage jenkins -> manage plugins -> advanced], test that it fixes the bug for you and let me know the results (here).
If it's all confirmed ok then I'll release the fix officially.

**Comment by pjdarton** [comment] 2019-10-01 10:48
...in the meantime, if you could check the code changes (in #752) then that would be helpful - it would be rather embarrassing if the fix for this was also buggy... :wink:

**Comment by php50350** [comment] 2019-10-01 13:36
Thank you for taking a quick response to fix the issue. I did a quick test using the updated plugin in my system and it works fine :)

**Comment by pjdarton** [comment] 2019-10-01 14:19
OK, thanks for confirming the fix.
I've merged the code changes into master and this will be fixed in the next release.

**Closed by pjdarton** 2019-10-01 14:19 UTC
Labels: bug

**Comment by pjdarton** [comment] 2019-11-22 18:38
Code changes went into released of docker-plugin version 1.1.9
