### ISSUE TITLE
is this plugin DEAD?

### ISSUE THREAD

**Issue by h0nIg** [jenkinsci/docker-plugin#482] opened 2017-03-04 19:06 UTC
there are a lot of open pull requests and issues. i came across this fact because https://github.com/jenkinsci/docker-plugin/pull/409 is very anoying and no body cares about that issue / no solution until now.

**Comment by eaglerainbow** [comment] 2017-03-04 22:20
Well, concerning #409: Closing the PR was a mistake by me. 
However, whether maintainability is still ensured for the project I don't know - I am not a member of the github project, but only "just another contributor" :)

**Comment by eaglerainbow** [comment] 2017-03-04 22:37
BTW: I even find #479 much more annoying than #409  :stuck_out_tongue_winking_eye:
For #409 there is the workaround that you may tag a version of a docker image multiple times (thus generating different names for it). Ideally, the tag's name includes the name of the Jenkins server which is creating the container. This tricks then the docker-plugin: it only counts the containers for the single tag...
#479 is much more critical to me: Each time the Jenkins server is restarted, the fix needs to be applied again... I only found a fix for the problem just recently.

**Comment by h0nIg** [comment] 2017-03-04 23:05
@KostyaSha could you please clarify that your fork of this plugin contains fixed for #409 / #479 ?
https://github.com/KostyaSha/yet-another-docker-plugin

**Comment by KostyaSha** [comment] 2017-03-04 23:06
@h0nIg fixed long time ago, feel free to try.

**Comment by h0nIg** [comment] 2017-03-04 23:13
@KostyaSha please update links on https://wiki.jenkins-ci.org/display/JENKINS/Yet+Another+Docker+Plugin git links pointing to 404

**Comment by KostyaSha** [comment] 2017-03-04 23:14
@h0nIg that's not my issue, this wiki page macros has no configurations. That's why links listed below.

**Comment by h0nIg** [comment] 2017-03-04 23:15
@KostyaSha maybe mark them with BIG RED LETTERS so people will notice them :)

**Comment by eaglerainbow** [comment] 2017-03-04 23:31
@magnayn Are you still with this plugin?

**Comment by oleg-nenashev** [comment] 2017-03-05 18:04
@KostyaSha good news is that we're moving from Wiki to jenkins.io and its plugin site, bad news is that projects hosted outside the jenkinsci org will unlikely become first-class citizens anyway. So the proposal from @h0nIg is reasonable if you do not want to move

**Comment by KostyaSha** [comment] 2017-03-05 18:05
I think i created issue in issues long time ago. So i'm done ;)

**Comment by thomassuckow** [comment] 2017-03-06 16:03
I've been looking at moving to Docker Pipeline. https://wiki.jenkins-ci.org/display/JENKINS/CloudBees+Docker+Pipeline+Plugin

But I need to get a server built that is a Jenkins slave and has docker on it.

**Comment by magnayn** [comment] 2017-03-06 16:27
I'm on Holiday ATM

If someone wants to comaintain I'm happy to give them access.

@ndeloof  ?

**Comment by erik-am** [comment] 2017-03-16 10:03
Some issues were already fixed in the master branch but have not been released yet (see https://github.com/jenkinsci/docker-plugin/issues/480)

**Comment by gamma** [comment] 2017-06-27 05:17
@magnayn it would be great if some more people volunteered to co-maintain. If there was a review process this would actually work?

Hands up people. Who is willing to move forward and do something with this plugin?

**Comment by fboudra** [comment] 2017-06-27 07:17
@gamma as pointed multiple times in this thread, there's alternative: https://github.com/KostyaSha/yet-another-docker-plugin

Migrating is trivial due to their common ancestor.

**Comment by gamma** [comment] 2017-06-27 07:19
Though I contributed, It does not work as expected in our environment and tends to be error prone ...

**Comment by eaglerainbow** [comment] 2017-06-28 18:56
> Hands up people. Who is willing to move forward and do something with this plugin?

I would volunteer to participate in one or the other code review if that helps along...

**Comment by erik-am** [comment] 2017-06-29 07:29
I already switched to https://github.com/KostyaSha/yet-another-docker-plugin

I'd say let's bundle forces to improve that one, at least it's frequently updated. Having two docker cloud plugins only adds confusion.

**Comment by thomassuckow** [comment] 2017-06-29 13:21
Just 2?

https://github.com/jenkinsci/docker-workflow-plugin  This one I think has the most promise in the long run. Mainly because I think jenkins workflow simplifies describing the build environment desired.

https://wiki.jenkins.io/display/JENKINS/CloudBees+Docker+Custom+Build+Environment+Plugin
https://wiki.jenkins.io/display/JENKINS/CloudShare+Docker-Machine+Plugin
https://wiki.jenkins.io/display/JENKINS/Docker+Slaves+Plugin
https://wiki.jenkins.io/display/JENKINS/CloudBees+Docker+Build+and+Publish+plugin

**Comment by KostyaSha** [comment] 2017-06-29 13:27
ENV tricks and slaves without cloud exist in YAD, but hidden for user usage. Docker CB plugins are broken by design with CLI wrapping for slaves usage, only makes sense for single command binary call wrappers. So they are all needed for those who think that do right docker features :D I made docker-plugin great in stephenc's rating, but can say now that it has a lot other design issues.

**Comment by ndeloof** [comment] 2017-09-11 11:29
Closing this issue.
Plugin is still alive, I volunteered to maintain it.

**Closed by ndeloof** 2017-09-11 11:29 UTC
