### ISSUE TITLE
Docker-Plugin kills containers before they are fully started up

### ISSUE THREAD

**Issue by janitza-jamu** [jenkinsci/docker-plugin#75] opened 2014-08-07 12:58 UTC
When a Docker container based Jenkins slave is needed for a labeled job, I observed the following behavior:
* more than one  container gets started at nearly the same time
* the first and maybe the second container get killed before they are fully started up
* in the beginning during the connection of a slave to the master, the slave is temporarily marked offline until the slave ist ready to accept jobs. During this time period the container or respectively the slave gets canceled by the docker-plugin due to not accepting tasks.
* The Retention Strategy of the docker-plugin is busy checking the first two started containers for readiness and therefore the third started container has enough time to fully get started up, before it gets checked and probably killed by the Retention Strategy.

Is there a way to specify the retries for the readiness or the time period during the checks? Maybe i just configured it wrong?

Tested with version 0.7.

**Comment by maxfields2000** [comment] 2015-06-17 12:47
This problem still exists in the 0.9 release.  Here's my stack trace:

Jun 17, 2015 12:43:16 PM WARNING hudson.slaves.NodeProvisioner$2 run
Provisioned slave Image of dockers.tf.xxxxx.com/mstewart/stresstestslave failed to launch
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.io.IOException: Slave failed to connect, even though the launcher didn't report it. See the log output for details.
	at shaded.com.google.common.base.Throwables.propagate(Throwables.java:160)
	at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:228)
	at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:201)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: java.io.IOException: Slave failed to connect, even though the launcher didn't report it. See the log output for details.
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:221)
	... 6 more
Caused by: java.io.IOException: Slave failed to connect, even though the launcher didn't report it. See the log output for details.
	at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:267)
	... 5 more

Jun 17, 2015 12:43:16 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud provision
Asked to provision 1 slave(s) for: mytestlabel
Jun 17, 2015 12:43:16 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud provision
Will provision "dockers.tf.xxxxx.com/mstewart/stresstestslave" for: mytestlabel
Jun 17, 2015 12:43:16 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud addProvisionedSlave
Provisioning "dockers.tf.xxxxx.com/mstewart/stresstestslave" number 1 on "Docker"; Total containers: 2
Jun 17, 2015 12:43:16 PM INFO hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
Started provisioning Image of dockers.tf.xxxxx.com/mstewart/stresstestslave from Docker with 1 executors. Remaining excess workload: 0
Jun 17, 2015 12:43:16 PM WARNING hudson.slaves.NodeProvisioner$2 run
Provisioned slave Image of dockers.tf.xxxxx.com/mstewart/stresstestslave failed to launch
java.lang.NullPointerException
	at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:221)
	at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:201)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Jun 17, 2015 12:43:16 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud provision


I've tried this against Docker 1.5 and Docker 1.6.  Same issues.  The nodes are litterally spinning up and down fast, multiple times, before one manages to connect and run. It basically looks like it just needs to wait longer.

**Comment by maxfields2000** [comment] 2015-06-17 14:25
Investigating further it seems to happen if I start several jobs at once that need to spin up containers. Doesn't matter if they are part of the same docker host or not. If there's multiple jobs in queue waiting for a slave to spin up, Jenkins can end up cycling a lot of containers before one starts.

If I start them one at a time, wait for their containers to start, then start the next job, things go very smoothly and I don't get long container spin up loops.

**Comment by maxfields2000** [comment] 2015-06-17 15:13
Forgot to add:

Jenkins v1.609.1
Docker Plugin 0.90

Jenkins is running in Docker 1.6 on Debian using Java 8.

I've tried it pointed to Docker Swarm v0.20 and v0.30 as well as reproduced it pointing straight at a single Dockerhost running Docker 1.6.  Behavior is the same regardless of endpoint.

**Comment by brandocorp** [comment] 2015-06-30 22:56
We are currently seeing this same issue when a bulk number of jobs are added to the queue. The fewer the jobs, the more likely it is to spin up and connect to a container. It seems to be when the number being requested gets above 10 or so containers.

**Comment by KostyaSha** [comment] 2015-07-03 01:41
Will be fixed/improved after #234 merge

**Closed** 2015-07-17 18:14 UTC
Labels: connect
