### ISSUE TITLE
Error starting new containers with Jenkins 2.266

### ISSUE THREAD

**Issue by JChrist** [jenkinsci/docker-plugin#819] opened 2020-11-12 13:09 UTC
docker-plugin version you use: 1.2.1
jenkins version you use: 2.266
docker engine version you use: 19.03.13

After upgrading Jenkins to v2.266, any new docker containers started for build jobs are reporting to be offline (and new ones keep spawning). The error output of a failed container (reported as offline) is:
```
Connecting to docker container 0d169f9ec1338b1af683d0b512fd112621d13f1b4288eb1f17a12faf6eebc734, running command java -jar /root/remoting-4.6.jar -noReconnect -noKeepAlive -slaveLog /root/agent.log
HTTP/1.1 101 UPGRADED
Content-Type: application/vnd.docker.raw-stream
Connection: Upgrade
Upgrade: tcp
Api-Version: 1.40
Docker-Experimental: false
Ostype: linux
Server: Docker/19.03.13 (linux)
ERROR: Unexpected error in launching an agent. This is probably a bug in Jenkins
Also:   java.lang.Throwable: launched here
	at hudson.slaves.SlaveComputer._connect(SlaveComputer.java:283)
	at hudson.model.Computer.connect(Computer.java:435)
	at com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy.start(DockerOnceRetentionStrategy.java:80)
	at com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy.start(DockerOnceRetentionStrategy.java:35)
	at hudson.model.AbstractCIBase.updateComputer(AbstractCIBase.java:162)
	at hudson.model.AbstractCIBase.access$000(AbstractCIBase.java:44)
	at hudson.model.AbstractCIBase$2.run(AbstractCIBase.java:224)
	at hudson.model.Queue._withLock(Queue.java:1401)
	at hudson.model.Queue.withLock(Queue.java:1278)
	at hudson.model.AbstractCIBase.updateComputerList(AbstractCIBase.java:207)
	at jenkins.model.Jenkins.updateComputerList(Jenkins.java:1631)
	at jenkins.model.Nodes$2.run(Nodes.java:139)
	at hudson.model.Queue._withLock(Queue.java:1401)
	at hudson.model.Queue.withLock(Queue.java:1278)
	at jenkins.model.Nodes.addNode(Nodes.java:135)
	at jenkins.model.Jenkins.addNode(Jenkins.java:2154)
	at com.nirima.jenkins.plugins.docker.DockerCloud.robustlyAddNodeToJenkins(DockerCloud.java:445)
	at com.nirima.jenkins.plugins.docker.DockerCloud.access$000(DockerCloud.java:68)
	at com.nirima.jenkins.plugins.docker.DockerCloud$1.run(DockerCloud.java:381)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.io.EOFException: unexpected stream termination
	at hudson.remoting.ChannelBuilder.negotiate(ChannelBuilder.java:415)
	at hudson.remoting.ChannelBuilder.build(ChannelBuilder.java:360)
	at hudson.slaves.SlaveComputer.setChannel(SlaveComputer.java:425)
	at hudson.slaves.SlaveComputer.setChannel(SlaveComputer.java:392)
	at io.jenkins.docker.connector.DockerComputerAttachConnector$DockerAttachLauncher.launch(DockerComputerAttachConnector.java:319)
	at hudson.slaves.DelegatingComputerLauncher.launch(DelegatingComputerLauncher.java:64)
	at io.jenkins.docker.connector.DockerDelegatingComputerLauncher.launch(DockerDelegatingComputerLauncher.java:37)
	at hudson.slaves.SlaveComputer.lambda$_connect$0(SlaveComputer.java:294)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:80)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by pjdarton** [comment] 2020-11-12 16:19
This looks like a duplicate of #818

**Closed by pjdarton** 2020-11-12 16:19 UTC
