### ISSUE TITLE
Unable to specify private docker registry in Configure Jenkins -> Cloud

### ISSUE THREAD

**Issue by AshwinPai1981** [jenkinsci/docker-plugin#712] opened 2019-01-03 22:02 UTC
- [1.1.5 ] docker-plugin version you use

 - [2.138 ] jenkins version you use

 - [ ] docker engine version you use
Version = 1.12.6, API Version = 1.24

 - [ ] stack trace / logs / any technical details that could help diagnose this issue

We host a private docker registry from which i want to pull images. Unfortunately providing the Docker Image as <registry>/imagename:latest and have also provided the credentials id to <registry>. However I get the below error when the plugin tries to pull down the image. I can also see that the registry URL seems to be null in the 

`Error in provisioning; template='DockerTemplate{configVersion=2, labelString='docker-iib-build', connector=io.jenkins.docker.connector.DockerComputerSSHConnector@1596d10b, remoteFs='/home/jenkins', instanceCap=2147483647, mode=EXCLUSIVE, retentionStrategy=com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy@62fe5c4, dockerTemplateBase=DockerTemplateBase{image='**registry.xxxxxxx/integration_automation/int-docker-jenkins-slave-iib-build**', pullCredentialsId='xxxxxxx', registry=### **DockerRegistryEndpoint[null;credentialsId=xxxxxxx]**, dockerCommand='', hostname='', dnsHosts=[], network='', volumes=[/home/cloud-user/jenkins:/home/jenkins], volumesFrom2=[], environment=[], bindPorts='', bindAllPorts=true, memoryLimit=null, memorySwap=null, cpuShares=null, shmSize=null, privileged=false, tty=false, macAddress='null', extraHosts=[]}, removeVolumes=false, pullStrategy=PULL_LATEST, nodeProperties=[], disabled=BySystem,0 ms,9.9 sec,Template provisioning failed.}' for cloud='docker-iib-build'
com.github.dockerjava.api.exception.NotFoundException: {"message":"No such image: registry.gitlab.mycompany.com/gitlab_group/int-docker-jenkins-slave-iib-build:latest"}

	at com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:103)
	at com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:33)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
Caused: com.github.dockerjava.api.exception.DockerClientException: Could not pull image: registry.gitlab.mycompany.com/gitlab_group/int-docker-jenkins-slave-iib-build:latest
	at com.nirima.jenkins.plugins.docker.DockerTemplate.pullImage(DockerTemplate.java:511)
	at com.nirima.jenkins.plugins.docker.DockerTemplate.provisionNode(DockerTemplate.java:519)
	at com.nirima.jenkins.plugins.docker.DockerCloud$1.run(DockerCloud.java:365)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Jan 03, 2019 9:58:20 PM WARNING hudson.slaves.NodeProvisioner$2 run
Unexpected exception encountered while provisioning agent Image of registry.gitlab.mycompany.com/gitlab_group/int-docker-jenkins-slave-iib-build
com.github.dockerjava.api.exception.NotFoundException: {"message":"No such image: registry.gitlab.mycompany.com/gitlab_group/int-docker-jenkins-slave-iib-build:latest"}

	at com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:103)
	at com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:33)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
Caused: com.github.dockerjava.api.exception.DockerClientException: Could not pull image: registry.gitlab.mycompany.com/gitlab_group/int-docker-jenkins-slave-iib-build:latest
	at com.nirima.jenkins.plugins.docker.DockerTemplate.pullImage(DockerTemplate.java:511)
	at com.nirima.jenkins.plugins.docker.DockerTemplate.provisionNode(DockerTemplate.java:519)
	at com.nirima.jenkins.plugins.docker.DockerCloud$1.run(DockerCloud.java:365)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by pjdarton** [comment] 2019-01-07 14:58
Are you 100% sure you're specifying the image name correctly?
e.g. Where I work, we run private registries as well and our "Docker Image" strings are of the form FQHN:portNumber/imageName:version, e.g. `myhostname.mydomain.com:5000/jenkins_slave:latest`.
The image name that you listed in the exception trace, `registry.gitlab.kfplc.com/integration_automation/int-docker-jenkins-slave-iib-build`, has an additional `/integration_automation` section in it (and doesn't have `:latest` either ... which shouldn't be necessary but it might be worth trying).

We also use Artifactory as a docker registry which (like gitlab) divides access into project areas and for _that_, the image names are of the form `myproject.myartifactoryhost.mydomain.com/jenkins_slave:latest`, and there's some reverse-proxy magic happening at the Artifactory end to ensure that HTTP requests to `myproject.myartifactoryhost.mydomain.com` end up going to `myartifactoryhost.mydomain.com` with the URL re-written to be within project `myproject`.  Maybe GitLab works the same way?

FYI the plugin talks to the docker host's API and tells it to do the `docker pull` so any "not found" errors are coming from the docker host and then being reported by Jenkins.  To debug this, I'd suggest you go onto the docker host's command line and verify that `docker login registry.gitlab.kfplc.com && docker pull registry.gitlab.kfplc.com/integration_automation/int-docker-jenkins-slave-iib-build:latest` works as expected - I suspect that the Jenkins docker-plugin is merely being the bearer of bad news here rather than the cause of it.

**Comment by pjdarton** [comment] 2019-02-06 17:26
@InTheCloudDan as discussed (elsewhere) this NullPointerException is an unrelated error that'll be FITNR.

**Comment by AshwinPai1981** [comment] 2019-08-07 13:29
Sorry I have been silent after i posted the issue. 
@pjdarton - The suggestion you have given is wast I have been doing as a workaround. I.e on the docker host i login and pull the image down, there after the jenkins docker plugin finds the image on the docker host from the cache. It looked like to me that when the image is not cached it is unable to pull the image down from the registry.

**Comment by robincsmith** [comment] 2019-08-29 11:23
@AshwinPai1981  Are you certain the credential is set correctly in the Jenkins master?

I got stuck on this problem for a while. I had the same symptoms and went through the same steps as you - pulling the image onto the local machine using (what I thought was) the same credentials as stored on the Jenkins master, and that worked fine. So I was utterly confused by the error.

In the end I updated the credential by hand in the Jenkins UI and the plugin worked fine again. You may have already tried that, but worth trying if not. I'm using the Configuration-as-Code plugin to set my credentials though, so it may not relate to your issue.

**Comment by AshwinPai1981** [comment] 2019-10-04 11:01
@robincsmith  - I have the credentials registered in the credentials plugin via CASC plugin. And the same cred is used for normal gitlab clones/pulls/fetches which works.

@pjdarton - Any idea, how the plugin resolves the image registry host? Does it parse the FQN of the image to get the reistry name? Looking at the log, I can see that the registry URL seems to be null in the **DockerRegistryEndpoint** and there is no provision in the jenkins UI to specify the registry URL.
Regarding your setup, are you sure its working because there might be a cached image on your docker host? In my case i hadn't realised in the beginning that the image was being used from the cache. Its when i rebuilt the docker host I found this issue where the plugin was not downloading the image from the private registry.

**_Error_**
Error in provisioning; template='DockerTemplate{configVersion=2, labelString='docker-iib-build', connector=io.jenkins.docker.connector.DockerComputerSSHConnector@7ebd07b7, remoteFs='/home/jenkins', instanceCap=2147483647, mode=NORMAL, retentionStrategy=com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy@5ab5ef61, dockerTemplateBase=DockerTemplateBase{image='registry.gitlab.mycompany.com/namespase/imagename', pullCredentialsId='srv-gitlab', **_registry=DockerRegistryEndpoint[null;credentialsId=srv-gitlab]_**, dockerCommand='', hostname='', dnsHosts=[], network='', volumes=[], volumesFrom2=[], environment=[], bindPorts='', bindAllPorts=true, memoryLimit=null, memorySwap=null, cpuShares=null, shmSize=null, privileged=false, tty=false, macAddress='null', extraHosts=[]}, removeVolumes=false, pullStrategy=PULL_ALWAYS, nodeProperties=[], disabled=BySystem,0 ms,9.9 sec,Template provisioning failed.}' for cloud='docker-iib-build'
com.github.dockerjava.api.exception.NotFoundException: {"message":"No such image: registry.gitlab.mycompany.com/namespase/imagename:latest"}

Thanks and Regards
Ashwin

**Comment by Dohbedoh** [comment] 2020-07-27 08:36
Maybe the plugin should use https://github.com/jenkinsci/docker-commons-plugin/blob/docker-commons-1.17/src/main/java/org/jenkinsci/plugins/docker/commons/credentials/DockerRegistryEndpoint.java#L108-L137 to infer the registry URL.

**Comment by pjdarton** [comment] 2020-07-27 12:01
If you believe that it'd be better if it did this, feel free to create a PR.
In general, I'm all in favour of replacing lengthy custom code with a call out to an existing shared library.
The less code we have in this plugin (while still doing the same job), the less chance there is of bugs being present in _this_ code 😉

**Comment by Dohbedoh** [comment] 2020-07-27 12:52
After enabling debug logs for `com.github.dockerjava`, we can see something like this being posted by the docker plugin:

```
[id: 0xf8d1d7c6, L:null - R:/var/run/docker.sock] WRITE: DefaultHttpRequest(decodeResult: success, version: HTTP/1.1)
POST /images/create?fromImage=my.docker.registry%2Fjenkins%2Finbound%3Alatest HTTP/1.1
content-length: 0
connection: keep-alive
accept-encoding: gzip
X-Registry-Auth: <base64EncodedCreds>
Host: DUMMY
accept: application/octet-stream
```

When we decode that `X-Registry-Auth: <base64EncodedCreds>`, we see something like this:

```
{"username":"<myCredentialsUser>","password":<myCredentialsPassword>,"serveraddress":"https://index.docker.io/v1/"}
```

That server address is the docker default registry (with the protocol by the way, but [not sure if that matters](https://github.com/docker-java/docker-java/blob/3.2.5/docker-java-api/src/main/java/com/github/dockerjava/api/model/AuthConfig.java#L15-L20) to be honest), not the `my.docker.registry`.

**Comment by 0x5e** [comment] 2022-09-30 15:15
Anything update?

**Comment by pjdarton** [comment] 2022-09-30 18:48
There's a linked PR that could fix it - you could try building that and using it.
That PR was blocked pending a PR to docker-common being merged ... which was (after a 2 year delay) merged last month.
If the original author of #807 is no longer able/willing to push things forwards then you could create your own PR based off that and finish the job now it's unblocked.
I'd be happy to merge in a PR once there's a consensus that it fixes things.

...but, as I no longer use this plugin myself, I'm not in a position to drive this forwards myself (hence why this plugin is "up for adoption"). Until a new maintainer is found, I can merge PRs and push out new releases, but as I can't test things myself anymore I have to be cautious when doing so😉

**Closed** 2023-05-25 19:07 UTC
