### ISSUE TITLE
UnsupportedOperationException when add a new template to all docker clouds

### ISSUE THREAD

**Issue by habib-the-sweet** [jenkinsci/docker-plugin#492] opened 2017-05-31 15:36 UTC
Hello. I have got a build failure when I'm trying to use 'Add a new template to all docker clouds' as a build step.

```
ERROR: Build step failed with exception
java.lang.UnsupportedOperationException
	at java.util.AbstractList.add(Unknown Source)
	at java.util.AbstractList.add(Unknown Source)
	at com.nirima.jenkins.plugins.docker.DockerCloud.addTemplate(DockerCloud.java:464)
	at com.nirima.jenkins.plugins.docker.builder.DockerBuilderNewTemplate.perform(DockerBuilderNewTemplate.java:125)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:730)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:490)
	at hudson.model.Run.execute(Run.java:1735)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:415)
Build step 'Add a new template to all docker clouds' marked build as failure
```

Jenkins ver. 2.63
Docker Plugin 0.16.2
Docker version 17.05.0-ce, build 89658be

**Comment by ndeloof** [comment] 2017-09-11 11:47
I even wonder why this "feature" exists. Can you please describe your use case ?

**Comment by habib-the-sweet** [comment] 2017-09-11 14:52
@ndeloof I want to build some dockerfile and add it to the template for using it container in another jenkins project.

**Comment by ndeloof** [comment] 2017-09-11 16:14
so I guess you want to update image being used by an existing template, right ?
Why not just push an updated tag then ?

**Comment by habib-the-sweet** [comment] 2017-09-27 21:37
No. I have not any templates and want to create it by this featue

**Comment by ndeloof** [comment] 2017-10-11 06:06
Sounds like a weird use-case. 
If you don't have any template set your cloud configuration is useless.
If you're looking for some way to automate template management, then better use jenkins CLI or REST api (or groovy scripts) vs this odd builder. This is a very uncommon pattern to get a job update jenkins configuration this way.

There's actually a permission issue doing this : job has to run with administrator permission so it is legitimate to update the cloud configuration.

**Comment by ndeloof** [comment] 2017-10-13 09:25
Root cause is your Cloud seems to be created without any template, as such the implementation is some `Collections.emptyList()` (java.util.Collections.EmptyList) which is immutable.

I'm not sure to be pleased the plugin do support this feature. Such administrative operation packaged as a build step is something I never have seen before for other plugins. Can you please give me more details on your use-case ? Would help me understand the needs and possible alternatives.
Thanks

**Comment by ndeloof** [comment] 2017-10-13 09:25
fixed by https://github.com/jenkinsci/docker-plugin/commit/8a029729d1010c0c222893d23ca135f1dd89c9f3

**Closed by ndeloof** 2017-10-13 09:25 UTC
Labels: bug
